import type { ComboboxOption } from '@/components/ui';

const PORTS_DEPARTURE_RAW: string[] = [
  'Durres, Albania (ALDRZ)',
  'Algiers, Algeria (DZALG)',
  'Annaba, Algeria (DZAAE)',
  'Bejaia (Bougie), Algeria (DZBJA)',
  'Ghardaia, Algeria (DZGHA)',
  'Mostaganem, Algeria (DZMOS)',
  'Oran, Algeria (DZORN)',
  'Skikda, Algeria (DZSKI)',
  'Pago Pago, American Samoa (ASPPG)',
  'Cabinda, Angola (AOCAB)',
  'Lobito, Angola (AOLOB)',
  'Luanda, Angola (AOLAD)',
  'Namibe, Angola (AOMSZ)',
  'Soyo, Angola (AOSZA)',
  'Blowing Point, Anguilla (AIBLP)',
  'Antigua, Antigua and Barbuda (AGANU)',
  'Saint John\'s, Antigua and Barbuda (AGSJO)',
  'Bahia Blanca, Argentina (ARBHI)',
  'Buenos Aires, Argentina (ARBUE)',
  'Caleta Olivia, Argentina (ARCVI)',
  'Campana, Argentina (ARCMP)',
  'Comodoro Rivadavia, Argentina (ARCRD)',
  'Corrientes, Argentina (ARCNQ)',
  'Delta Dock, Argentina (ARDDC)',
  'Goya, Argentina (AROYA)',
  'La Plata, Argentina (ARLPG)',
  'Mar del Plata, Argentina (ARMDQ)',
  'Necochea, Argentina (ARNEC)',
  'Puerto Deseado, Argentina (ARPUD)',
  'Puerto Madryn, Argentina (ARPMY)',
  'Rio Cullen, Argentina (ARRIC)',
  'Rio Gallegos, Argentina (ARRGL)',
  'Rio Grande, Argentina (ARRGA)',
  'Rosario, Argentina (ARROS)',
  'San Antonio Este, Argentina (ARSAE)',
  'San Lorenzo, Argentina (ARSLO)',
  'San Nicolas de los Arroyos, Argentina (ARSNS)',
  'San Pedro, Argentina (ARSPD)',
  'Santa Fe, Argentina (ARSFN)',
  'Ushuaia, Argentina (ARUSH)',
  'Zarate, Argentina (ARZAE)',
  'Aruba, Aruba (AWAUA)',
  'Oranjestad, Aruba (AWORJ)',
  'Abbot Point, Australia (AUABP)',
  'Adelaide, Australia (AUADL)',
  'Ardrossan, Australia (AUARD)',
  'Bell Bay, Australia (AUBEL)',
  'Booby Island, Australia (AUBOO)',
  'Bremer Bay, Australia (AUBBY)',
  'Brisbane, Australia (AUBNE)',
  'Burnie, Australia (AUBWT)',
  'Cairns, Australia (AUCNS)',
  'Chittering, Australia (AUCHT)',
  'Darwin, Australia (AUDRW)',
  'Devonport, Australia (AUDPO)',
  'Fremantle, Australia (AUFRE)',
  'Gladstone, Australia (AUGLT)',
  'Gove, Australia (AUGOV)',
  'Hay Point, Australia (AUHPT)',
  'Hobart, Australia (AUHBA)',
  'Launceston, Australia (AULST)',
  'Melbourne, Australia (AUMEL)',
  'New Norfolk, Australia (AUNLK)',
  'Newcastle, Australia (AUNTL)',
  'Port Adelaide, Australia (AUPAE)',
  'Port Hedland, Australia (AUPHE)',
  'Port Kembla, Australia (AUPKL)',
  'Sydney, Australia (AUSYD)',
  'Townsville, Australia (AUTSV)',
  'Weipa, Australia (AUWEI)',
  'Hainfeld, Austria (ATLTX)',
  'Baku, Azerbaijan (AZBAK)',
  'Freeport, Bahamas (BSFPO)',
  'Nassau, Bahamas (BSNAS)',
  'Al Hidd, Bahrain (BHAHD)',
  'Bahrain, Bahrain (BHBAH)',
  'Khalifa Bin Salman, Bahrain (BHKBS)',
  'Manama, Bahrain (BHMAN)',
  'Sitrah, Bahrain (BHSIT)',
  'Chalna, Bangladesh (BDCHL)',
  'Chittagong, Bangladesh (BDCGP)',
  'Dhaka, Bangladesh (BDDAC)',
  'Mongla, Bangladesh (BDMGL)',
  'Bridgetown, Barbados (BBBGI)',
  'Minsk, Belarus (BYMSQ)',
  'Antwerpen, Belgium (BEANR)',
  'Bossuit, Belgium (BEBSU)',
  'Doel, Belgium (BEDEL)',
  'Gent (Ghent), Belgium (BEGNE)',
  'Oostende (Ostend), Belgium (BEOST)',
  'Zeebrugge, Belgium (BEZEE)',
  'Belize City, Belize (BZBZE)',
  'Cotonou, Benin (BJCOO)',
  'Hamilton, Bermuda (BMBDA)',
  'Southampton, Bermuda (BMSOU)',
  'Puerto Busch, Bolivia (BOPBU)',
  'Santa Cruz, Bolivia (BOSRZ)',
  'Road Town, Tortola, British Virgin Islands (VGRAD)',
  'Tortola, British Virgin Islands (VGTOV)',
  'Bandar Seri Begawan, Brunei Darussalam (BNBWN)',
  'Kuala Belait, Brunei Darussalam (BNKUB)',
  'Muara, Brunei Darussalam (BNMUA)',
  'Burgas, Bulgaria (BGBOJ)',
  'Varna, Bulgaria (BGVAR)',
  'Ouagadougou, Burkina Faso (BFOUA)',
  'Mindelo, Cabo Verde (CVMIN)',
  'Palmeira, Cabo Verde (CVPAL)',
  'Praia, Cabo Verde (CVRAI)',
  'Kampong Saom, Cambodia (KHKOS)',
  'Phnom Penh, Cambodia (KHPNH)',
  'Douala, Cameroon (CMDLA)',
  'Baie d\'Urfe, Canada (CABDU)',
  'Baie-Johan-Beetz, Canada (CABJO)',
  'Bathurst, Canada (CABAT)',
  'Becancour, Canada (CABEC)',
  'Brockville, Canada (CABCK)',
  'Burlington, Canada (CABRL)',
  'Calgary, Canada (CACAL)',
  'Collingwood, Canada (CACOL)',
  'Corner Brook, Canada (CACBK)',
  'Cornwall, Canada (CACWL)',
  'Cowichan Bay, Canada (CACCB)',
  'Crofton, Canada (CACRO)',
  'Dorval, Canada (CADOR)',
  'Drummondville, Canada (CADRU)',
  'Edmonton, Canada (CAEDM)',
  'Halifax, Canada (CAHAL)',
  'Hamilton, Canada (CAHAM)',
  'Harmac, Canada (CAHMC)',
  'Kingsville, Canada (CAKVL)',
  'Magog, Canada (CAMAG)',
  'Moncton, Canada (CAMNT)',
  'Montreal, Canada (CAMTR)',
  'Nanaimo, Canada (CANNO)',
  'New Westminster, Canada (CANWE)',
  'Niagara Falls, Canada (CANIA)',
  'North Bay, Canada (CANOR)',
  'Oakville, Canada (CAOAK)',
  'Odessa, Canada (CAODE)',
  'Oshawa, Canada (CAOSH)',
  'Pointe-Claire, Canada (CAPOI)',
  'Port Credit, Canada (CAPCR)',
  'Port Dover, Canada (CAPDV)',
  'Port Mellon, Canada (CAPML)',
  'Prince Rupert, Canada (CAPRR)',
  'Quebec, Canada (CAQUE)',
  'Saint-Catharines, Canada (CASCA)',
  'Saint-John, Canada (CASJB)',
  'Saint-John\'s, Canada (CASJF)',
  'Sarnia, Canada (CASNI)',
  'Saskatoon, Canada (CASAK)',
  'Sault-Sainte-Marie, Canada (CASSM)',
  'Sorel, Canada (CASOR)',
  'Stoney Creek, Canada (CASTC)',
  'Summerside, Canada (CASUM)',
  'Texada Island, Canada (CATEX)',
  'Thunder Bay, Canada (CATHU)',
  'Toronto, Canada (CATOR)',
  'Trenton, Canada (CATTC)',
  'Trois-Rivieres (Three Rivers), Canada (CATRR)',
  'Valleyfield, Canada (CAVLF)',
  'Vancouver, Canada (CAVAN)',
  'Winnipeg, Canada (CAWNP)',
  'Winona, Canada (CAWIN)',
  'Georgetown, Cayman Islands (KYGEC)',
  'Grand Cayman, Cayman Islands (KYGCM)',
  'Ancud, Chile (CLZUD)',
  'Antofagasta, Chile (CLANF)',
  'Arica, Chile (CLARI)',
  'Bahia San Gregorio, Chile (CLBAG)',
  'Barquito, Chile (CLBAR)',
  'Cabo Negro, Chile (CLCNX)',
  'Calbuco, Chile (CLCBC)',
  'Caldera, Chile (CLCLD)',
  'Caleta Coloso, Chile (CLCCL)',
  'Castro, Chile (CLWCA)',
  'Chacabuco, Chile (CLCHB)',
  'Chaiten, Chile (CLWCH)',
  'Chanaral, Chile (CLCNR)',
  'Coquimbo, Chile (CLCQQ)',
  'Coronel, Chile (CLCNL)',
  'Corral, Chile (CLCRR)',
  'Dalcahue, Chile (CLDCH)',
  'Guayacan, Chile (CLGYC)',
  'Huasco, Chile (CLHSO)',
  'Iquique, Chile (CLIQQ)',
  'Isla de Pascua, Chile (CLIPC)',
  'Las Ventanas, Chile (CLLVS)',
  'Lirquen, Chile (CLLQN)',
  'Los Vilos, Chile (CLLOS)',
  'Mejillones, Chile (CLMJS)',
  'Michilla, Chile (CLMCH)',
  'Patillos, Chile (CLPTI)',
  'Penco, Chile (CLPEO)',
  'Puerto Aisen, Chile (CLWPA)',
  'Puerto Angamos, Chile (CLPAG)',
  'Puerto Chacabuco, Chile (CLPCH)',
  'Puerto Montt, Chile (CLPMC)',
  'Puerto Natales, Chile (CLPNT)',
  'Puerto Williams, Chile (CLWPU)',
  'Punta Arenas, Chile (CLPUQ)',
  'Punta Chungo, Chile (CLPGO)',
  'Punta Padrones, Chile (CLPPD)',
  'Punta Patache, Chile (CLPPC)',
  'Quellon (Puerto Quellon), Chile (CLPTE)',
  'Quemchi, Chile (CLQMC)',
  'Quintero, Chile (CLQTV)',
  'San Antonio, Chile (CLSAI)',
  'San Vicente, Chile (CLCAP)',
  'San Vicente, Chile (CLSVE)',
  'Talcahuano, Chile (CLTAL)',
  'Talcahuano, Chile (CLTHO)',
  'Taltal, Chile (CLTTC)',
  'Tocopilla, Chile (CLTOQ)',
  'Tome, Chile (CLTOM)',
  'Valparaiso, Chile (CLVAP)',
  'Bayuquan, China (CNBAY)',
  'Beihai Fucheng, China (CNBHY)',
  'Beijiao, China (CNBJO)',
  'Beijiao, China (CNYQS)',
  'Changsha, China (CNCSX)',
  'Changshu, China (CNCGU)',
  'Chaozhou, China (CNCOZ)',
  'Chengdu, China (CNCTU)',
  'Chiwan, China (CNCWN)',
  'Chongqing, China (CNCKG)',
  'Da Chan Bay, China (CNDCB)',
  'Dagang, China (CNDAA)',
  'Dalian, China (CNDLC)',
  'Dongguan, China (CNDGG)',
  'Doumen, China (CNDOU)',
  'Fangcheng, China (CNFAN)',
  'Foshan, China (CNFOS)',
  'Fuqing, China (CNFUG)',
  'Fuyong, China (CNFNG)',
  'Fuzhou, China (CNFOC)',
  'Gaoming, China (CNGOM)',
  'Gongming, China (CNGOG)',
  'Gongyi, China (CNGGY)',
  'Guangzhou, China (CNCAN)',
  'Guigang, China (CNGUG)',
  'Haikou, China (CNHAK)',
  'Haimen, China (CNHME)',
  'Hangzhou, China (CNHGH)',
  'Hebei, China (CNHEB)',
  'Heshan, China (CNHSN)',
  'Huadu, China (CNHDU)',
  'Huangpu, China (CNHUA)',
  'Huizhou, China (CNHUI)',
  'Huludao, China (CNHUD)',
  'Humen, China (CNHMN)',
  'Jian, China (CNJIN)',
  'Jiangmen, China (CNJMN)',
  'Jiangyin, China (CNJIA)',
  'Jiao Xin, China (CNJXN)',
  'Jieyang Chaoshan, China (CNSWA)',
  'Jingzhou, China (CNJGZ)',
  'Jinzhou, China (CNJNZ)',
  'Jiujiang, China (CNJIU)',
  'Jiuzhou, China (CNJZU)',
  'Kaiping, China (CNKPN)',
  'Kunming, China (CNKMG)',
  'Lanshi, China (CNLAN)',
  'Lanshi, China (CNLSI)',
  'Lianhuashan, China (CNLIH)',
  'Lianyungang, China (CNLYG)',
  'Liuzhou, China (CNLZH)',
  'Longhua, China (CNLGH)',
  'Longkou, China (CNLKU)',
  'Maoming, China (CNMMI)',
  'Mawan, China (CNMWN)',
  'Mawei, China (CNMAW)',
  'Mianyang, China (CNMYG)',
  'Nanchang, China (CNKHN)',
  'Nangang, China (CNNGG)',
  'Nanhai, China (CNNAH)',
  'Nanjing, China (CNNKG)',
  'Nanning, China (CNNNG)',
  'Nansha, China (CNNSA)',
  'Nantong, China (CNNTG)',
  'Ningbo, China (CNNGB)',
  'Putian, China (CNPUT)',
  'Qianwan, China (CNQAW)',
  'Qingdao, China (CNTAO)',
  'Qingyuan, China (CNQYN)',
  'Qinhuangdao, China (CNSHP)',
  'Quanzhou, China (CNQZJ)',
  'Rizhao, China (CNRZH)',
  'Rongqi, China (CNROQ)',
  'Sanbu, China (CNSBU)',
  'Sanshan (Nanhai), China (CNSSH)',
  'Sanshui, China (CNSJQ)',
  'Shanghai, China (CNSHA)',
  'Shantou, China (CNSTG)',
  'Shanwei, China (CNSWE)',
  'Shatian, China (CNSIN)',
  'Shekou, China (CNSHK)',
  'Shenwan, China (CNSNW)',
  'Shenzhen Baoan, China (CNSZX)',
  'Shiqiao, China (CNPNY)',
  'Shuidong, China (CNSDG)',
  'Shunde, China (CNSUD)',
  'Suzhou, China (CNSZH)',
  'Taicang, China (CNTAG)',
  'Taicheng (Taishan), China (CNTHG)',
  'Taiping, China (CNTAP)',
  'Taizhou, China (CNTZO)',
  'Tianjin, China (CNTSN)',
  'Tianjin, China (CNTXG)',
  'Wanzai, China (CNWAZ)',
  'Weihai, China (CNWEI)',
  'Wenzhou, China (CNWNZ)',
  'Wuhan, China (CNWUH)',
  'Wuhu, China (CNWHI)',
  'Xiamen, China (CNXMN)',
  'Xiaolan, China (CNXIL)',
  'Xinfeng, China (CNXAB)',
  'Xingang, China (CNXGA)',
  'Xinhui, China (CNXIN)',
  'Xintang, China (CNXIT)',
  'Yangjiang, China (CNYJI)',
  'Yangpu, China (CNYPG)',
  'Yangshan, China (CNYAN)',
  'Yangzhou, China (CNYZH)',
  'Yantai, China (CNYNT)',
  'Yantian, China (CNYTN)',
  'Yichang, China (CNYIC)',
  'Yingkou, China (CNYIK)',
  'Yunfu, China (CNYNF)',
  'Zhangjiagang, China (CNZJG)',
  'Zhanjiang Potou, China (CNZHA)',
  'Zhaoqing, China (CNZQG)',
  'Zhapu (Zhejiang), China (CNZAP)',
  'Zhenjiang, China (CNZHE)',
  'Zhongshan, China (CNZSN)',
  'Zhoushan, China (CNZOS)',
  'Zhuhai, China (CNZUH)',
  'Barranquilla, Colombia (COBAQ)',
  'Buenaventura, Colombia (COBUN)',
  'Cartagena, Colombia (COCTG)',
  'Puerto Bolivar, Colombia (COPBO)',
  'Santa Marta, Colombia (COSMR)',
  'Tumaco, Colombia (COTCO)',
  'Moroni, Comoros (KMYVA)',
  'Mutsamudu, Anjouan, Comoros (KMMUT)',
  'Caldera, Costa Rica (CRCAL)',
  'Golfito, Costa Rica (CRGLF)',
  'Moin, Costa Rica (CRMOB)',
  'Puerto Caldera, Costa Rica (CRPCA)',
  'Puerto Limon, Costa Rica (CRLIO)',
  'Puntarenas, Costa Rica (CRPAS)',
  'San Jose, Costa Rica (CRSJO)',
  'Dubrovnik, Croatia (HRDBV)',
  'Ploce, Croatia (HRPLE)',
  'Rijeka, Croatia (HRRJK)',
  'Split, Croatia (HRSPU)',
  'La Habana, Cuba (CUHAV)',
  'Mariel, Cuba (CUMAR)',
  'Matanzas, Cuba (CUQMA)',
  'Santiago de Cuba, Cuba (CUSCU)',
  'Limassol, Cyprus (CYLMS)',
  'Nicosia, Cyprus (CYNIC)',
  'Paphos, Cyprus (CYPFO)',
  'Boma, Democratic Republic Of The Congo (CDBOA)',
  'Matadi, Democratic Republic Of The Congo (CDMAT)',
  'Aalborg, Denmark (DKAAL)',
  'Aarhus, Denmark (DKAAR)',
  'Assens, Denmark (DKASN)',
  'Esbjerg, Denmark (DKEBJ)',
  'Fredericia, Denmark (DKFRC)',
  'Helsingor, Denmark (DKHLS)',
  'Hirtshals, Denmark (DKHIR)',
  'Holstebro, Denmark (DKHSB)',
  'Kalundborg, Denmark (DKKAL)',
  'Kerteminde, Denmark (DKKTD)',
  'Kobenhavn, Denmark (DKCPH)',
  'Nyborg, Denmark (DKNBG)',
  'Odense, Denmark (DKODE)',
  'Rungsted, Denmark (DKRUG)',
  'Skagen, Denmark (DKSKA)',
  'Svendborg, Denmark (DKSVE)',
  'Djibouti, Djibouti (DJJIB)',
  'Roseau, Dominica (DMRSU)',
  'Caucedo, Dominican Republic (DOCAU)',
  'Manzanillo, Dominican Republic (DOMAN)',
  'Puerto Plata, Dominican Republic (DOPOP)',
  'Rio Haina, Dominican Republic (DOHAI)',
  'San Pedro de Macoris, Dominican Republic (DOSPM)',
  'Santo Domingo, Dominican Republic (DOSDQ)',
  'Bahia de Caraquez, Ecuador (ECBHA)',
  'Chanduy, Ecuador (ECCHA)',
  'Esmeraldas, Ecuador (ECESM)',
  'Guayaquil, Ecuador (ECGYE)',
  'La Libertad, Ecuador (ECLLD)',
  'Manta, Ecuador (ECMEC)',
  'Monteverde, Ecuador (ECMTV)',
  'Puerto Bolivar, Ecuador (ECPBO)',
  'Ain Sukhna, Egypt (EGAIS)',
  'As Suways (Suez), Egypt (EGSUZ)',
  'Dumyat (Damietta), Egypt (EGDAM)',
  'El Dekheila, Egypt (EGEDK)',
  'El Iskandariya (Alexandria), Egypt (EGALY)',
  'Port Said, Egypt (EGPSD)',
  'Acajutla, El Salvador (SVAQJ)',
  'La Libertad, El Salvador (SVLLD)',
  'La Union, El Salvador (SVLUN)',
  'San Salvador, El Salvador (SVSAL)',
  'Bata, Equatorial Guinea (GQBSG)',
  'Malabo, Equatorial Guinea (GQSSG)',
  'Assab, Eritrea (ERASA)',
  'Massawa (Mitsiwa), Eritrea (ERMSW)',
  'Haldi, Estonia (EEHLD)',
  'Muuga, Estonia (EEMUG)',
  'Tallinn, Estonia (EETLL)',
  'Port Stanley, Falkland Islands (FKPSY)',
  'Thorshavn, Faroe Islands (FOTHO)',
  'Lautoka, Fiji (FJLTK)',
  'Suva, Fiji (FJSUV)',
  'Bjorneborg (Pori), Finland (FIPOR)',
  'Fredrikshamn (Hamina), Finland (FIHMN)',
  'Hango (Hanko), Finland (FIHKO)',
  'Helsingfors (Helsinki), Finland (FIHEL)',
  'Karleby (Kokkola), Finland (FIKOK)',
  'Kemi/Tornea (Kemi/Tornio), Finland (FIKEM)',
  'Kotka, Finland (FIKTK)',
  'Oulu, Finland (FIOLU)',
  'Rauma (Raumo), Finland (FIRAU)',
  'Tornea (Tornio), Finland (FITOR)',
  'Turku, Finland (FITKU)',
  'Bassens, France (FRBAS)',
  'Bayonne, France (FRBAY)',
  'Bordeaux, France (FRBOD)',
  'Boulogne-sur-Mer, France (FRBOL)',
  'Brest, France (FRBES)',
  'Chitry, France (FRHGT)',
  'Dieppe, France (FRDPE)',
  'Dunkerque, France (FRDKK)',
  'Fos-sur-Mer, France (FRFOS)',
  'Honfleur, France (FRHON)',
  'Javrezac, France (FRJAV)',
  'La Ciotat, France (FRLCT)',
  'La Groise, France (FROR6)',
  'La Pallice, France (FRLPE)',
  'La Planche, France (FRLPC)',
  'La Rochelle, France (FRLRH)',
  'Le Havre, France (FRLEH)',
  'Le Treport, France (FRLTR)',
  'Le Verdon-sur-Mer, France (FRLVE)',
  'Lorient, France (FRLRT)',
  'Marseille, France (FRMRS)',
  'Monteton, France (FRMT7)',
  'Montoir-de-Bretagne, France (FRMTX)',
  'Mundolsheim, France (FRMDH)',
  'Mus, France (FRUSJ)',
  'Nantes, France (FRNTE)',
  'Paris, France (FRPAR)',
  'Piriac-sur-Mer, France (FRPIR)',
  'Port-Vendres, France (FRPOV)',
  'Rouen, France (FRURO)',
  'Saint-Nazaire, France (FRSNR)',
  'Sete, France (FRSET)',
  'Toulon, France (FRTLN)',
  'Cayenne, French Guiana (GFCAY)',
  'Degrad des Cannes, French Guiana (GFDDC)',
  'Papeete, French Polynesia (PFPPT)',
  'Libreville, Gabon (GALBV)',
  'Owendo, Gabon (GAOWE)',
  'Port Gentil, Gabon (GAPOG)',
  'Banjul, Gambia (GMBJL)',
  'Batumi, Georgia (GEBUS)',
  'Poti, Georgia (GEPTI)',
  'Tbilisi, Georgia (GETBS)',
  'Bad Oeynhausen, Germany (DEBOY)',
  'Bahlingen, Germany (DEBEZ)',
  'Bingen am Rhein, Germany (DEBIN)',
  'Brake, Germany (DEBKE)',
  'Bramel, Germany (DEBRA)',
  'Bremen, Germany (DEBRE)',
  'Bremerhaven, Germany (DEBRV)',
  'Brunsbuttel, Germany (DEBRB)',
  'Burgstaaken/Fehmarn, Germany (DEBSK)',
  'Cuxhaven, Germany (DECUX)',
  'Dusseldorf, Germany (DEDUS)',
  'Elsfleth, Germany (DEELS)',
  'Emden, Germany (DEEME)',
  'Flensburg, Germany (DEFLF)',
  'Hamburg, Germany (DEHAM)',
  'Hamm, Germany (DEHMM)',
  'Harburg, Germany (DEHBU)',
  'Kiel, Germany (DEKEL)',
  'Kochendorf, Germany (DEKHO)',
  'Koln, Germany (DECGN)',
  'Kriegenbrunn, Germany (DEKGU)',
  'Leer, Germany (DELEE)',
  'Lubeck, Germany (DELBC)',
  'Mannheim, Germany (DEMHG)',
  'Nordenham, Germany (DENHA)',
  'Nordstrand, Germany (DENOR)',
  'Pfronten, Germany (DEPFR)',
  'Rostock, Germany (DERSK)',
  'Wedel, Germany (DEWED)',
  'Wilhelmshaven, Germany (DEWVN)',
  'Worms, Germany (DEWOR)',
  'Takoradi, Ghana (GHTKD)',
  'Tema, Ghana (GHTEM)',
  'Gibraltar, Gibraltar (GIGIB)',
  'Astakos, Greece (GRAST)',
  'Heraklion (Iraklion), Greece (GRHER)',
  'Kythira, Greece (GRKAP)',
  'Piraeus, Greece (GRPIR)',
  'Rhodes, Greece (GRRHO)',
  'Thessaloniki, Greece (GRSKG)',
  'Volos, Greece (GRVOL)',
  'Saint George\'s, Grenada (GDSTG)',
  'Basse-Terre, Guadeloupe (GPBBR)',
  'Gustavia, Guadeloupe (GPGUS)',
  'Pointe-a-Pitre, Guadeloupe (GPPTP)',
  'Saint Barthelemy, Guadeloupe (GPSBH)',
  'Guam, Guam (GUGUM)',
  'Champerico, Guatemala (GTCHR)',
  'Guatemala City, Guatemala (GTGUA)',
  'Puerto Barrios, Guatemala (GTPBR)',
  'Puerto Quetzal, Guatemala (GTPRQ)',
  'Puerto Santo Tomas de Castilla, Guatemala (GTSTC)',
  'Conakry, Guinea (GNCKY)',
  'Bissau, Guinea-Bissau (GWOXB)',
  'Georgetown, Guyana (GYGEO)',
  'Cap-Haitien, Haiti (HTCAP)',
  'Port-au-Prince, Haiti (HTPAP)',
  'Amapala, Honduras (HNAMP)',
  'La Ceiba, Honduras (HNLCE)',
  'Puerto Castilla, Honduras (HNPCA)',
  'Puerto Cortes, Honduras (HNPCR)',
  'Roatan, Honduras (HNRTB)',
  'San Lorenzo, Honduras (HNSLO)',
  'Tela, Honduras (HNTEA)',
  'Hong Kong, Hong Kong (HKHKG)',
  'Budapest, Hungary (HUBUD)',
  'Eskifjordur - hofn, Iceland (ISESK)',
  'Grundartangi, Iceland (ISGRT)',
  'Reykjavik, Iceland (ISREY)',
  'Agra, India (INAGR)',
  'Ahmedabad, India (INAMD)',
  'Bangalore, India (INBLR)',
  'Chennai (ex Madras), India (INMAA)',
  'Cochin, India (INCOK)',
  'Coimbatore, India (INCJB)',
  'Cuddalore, India (INCDL)',
  'Dadri, India (INDRI)',
  'Daman, India (INDAM)',
  'Goa, India (INGOI)',
  'Haldia, India (INHAL)',
  'Hyderabad, India (INHYD)',
  'Jaipur, India (INJAI)',
  'Jawaharlal Nehru (Nhava Sheva), India (INNSA)',
  'Jodhpur, India (INJDH)',
  'Kakinada, India (INKAK)',
  'Kandla, India (INIXY)',
  'Kanpur, India (INKNU)',
  'Kolkata (ex Calcutta), India (INCCU)',
  'Krishnapatnam, India (INKRI)',
  'Ludhiana, India (INLUH)',
  'Mangalore, India (INIXE)',
  'Marmagao (Marmugao), India (INMRM)',
  'Moradabad, India (INMOR)',
  'Mumbai (ex Bombay), India (INBOM)',
  'Mundra, India (INMUN)',
  'Nagpur, India (INNAG)',
  'New Delhi, India (INICD)',
  'Panipat, India (INPAP)',
  'Pipavav, India (INPAV)',
  'Pithampur, India (INPIR)',
  'Pune, India (INPNQ)',
  'Surat, India (INSTV)',
  'Tuticorin, India (INTUT)',
  'Veraval, India (INVVA)',
  'Visakhapatnam, India (INVTZ)',
  'Amamapare, Indonesia (IDAMA)',
  'Balikpapan, Indonesia (IDBPN)',
  'Banjarmasin, Indonesia (IDBDJ)',
  'Batam Island, Indonesia (IDBTM)',
  'Batu Ampal, Indonesia (IDBUR)',
  'Belanak Terminal, Indonesia (IDBNT)',
  'Belawan, Indonesia (IDBLW)',
  'Bitung, Indonesia (IDBIT)',
  'Buatan, Indonesia (IDBUN)',
  'Cigading, Indonesia (IDCIG)',
  'Jakarta, Indonesia (IDJKT)',
  'Jambi, Indonesia (IDDJB)',
  'Jayapura, Irian Jaya, Indonesia (IDDJJ)',
  'Kabil, Indonesia (IDKAB)',
  'Makassar, Indonesia (IDMAK)',
  'Medan, Indonesia (IDMES)',
  'Merak, Java, Indonesia (IDMRK)',
  'Padang, Indonesia (IDPDG)',
  'Palembang, Sumatra, Indonesia (IDPLM)',
  'Panjang, Indonesia (IDPJG)',
  'Panjang, Indonesia (IDPNJ)',
  'Pekanbaru, Indonesia (IDPKU)',
  'Perawang, Indonesia (IDPWG)',
  'Pontianak, Indonesia (IDPNK)',
  'Samarinda, Indonesia (IDSRI)',
  'Semarang, Indonesia (IDSRG)',
  'Sungai Pakning, Indonesia (IDSEQ)',
  'Surabaya, Indonesia (IDSUB)',
  'Taboneo, Indonesia (IDTAB)',
  'Tanjung Priok, Indonesia (IDTPP)',
  'Tebingtinggi, Indonesia (IDTTI)',
  'Teluk Betung, Indonesia (IDTBG)',
  'Ujung Pandang, Indonesia (IDUPG)',
  'Bandar Abbas, Iran (IRBND)',
  'Bandar Khomeini, Iran (IRBKM)',
  'Bushehr, Iran (IRBUZ)',
  'Chah Bahar, Iran (IRZBR)',
  'Khorramshahr, Iran (IRKHO)',
  'Umm Qasr, Iraq (IQUQR)',
  'Cork, Ireland (IEORK)',
  'Drogheda, Ireland (IEDRO)',
  'Dublin, Ireland (IEDUB)',
  'Foynes, Ireland (IEFOV)',
  'Galway, Ireland (IEGWY)',
  'Kinsale, Ireland (IEKLN)',
  'Waterford, Ireland (IEWAT)',
  'Ashdod, Israel (ILASH)',
  'Hadera, Israel (ILHAD)',
  'Haifa, Israel (ILHFA)',
  'Netanya, Israel (ILNAT)',
  'Ramat Gan, Israel (ILRMG)',
  'Tel Aviv-Yafo, Israel (ILTLV)',
  'Ancona, Italy (ITAOI)',
  'Augusta, Italy (ITAUG)',
  'Bari, Italy (ITBRI)',
  'Cagliari, Italy (ITCAG)',
  'Capri, Italy (ITPRJ)',
  'Catania, Italy (ITCTA)',
  'Civitavecchia, Italy (ITCVV)',
  'Crotone, Italy (ITCRV)',
  'Faenza, Italy (ITFAE)',
  'Gaeta, Italy (ITGAE)',
  'Genova, Italy (ITGOA)',
  'Gioia Tauro, Italy (ITGIT)',
  'La Spezia, Italy (ITSPE)',
  'Livorno, Italy (ITLIV)',
  'Milano, Italy (ITMIL)',
  'Modena, Italy (ITMOD)',
  'Monfalcone, Italy (ITMNF)',
  'Napoli, Italy (ITNAP)',
  'Padova, Italy (ITPDA)',
  'Palermo, Italy (ITPMO)',
  'Pesaro, Italy (ITPES)',
  'Pescara, Italy (ITPSR)',
  'Porto Garibaldi, Italy (ITPGA)',
  'Portoscuso, Italy (ITPVE)',
  'Ravenna, Italy (ITRAN)',
  'Salerno, Italy (ITSAL)',
  'Savona, Italy (ITSVN)',
  'Taranto, Italy (ITTAR)',
  'Torino, Italy (ITTRN)',
  'Trapani, Italy (ITTPS)',
  'Trieste, Italy (ITTRS)',
  'Vado Ligure, Italy (ITVDL)',
  'Venezia, Italy (ITVCE)',
  'Viareggio, Italy (ITVIA)',
  'Abidjan, Ivory Coast (CIABJ)',
  'San-Pedro, Ivory Coast (CISPY)',
  'Kingston, Jamaica (JMKIN)',
  'Montego Bay, Jamaica (JMMBJ)',
  'Ocho Rios, Jamaica (JMOCJ)',
  'Port Kaiser, Jamaica (JMPKS)',
  'Aburatsu, Japan (JPABU)',
  'Akita, Japan (JPAXT)',
  'Aomori, Japan (JPAOJ)',
  'Chiba, Japan (JPCHB)',
  'Fukuyama, Japan (JPFKY)',
  'Hachinohe, Japan (JPHHE)',
  'Hakata/Fukuoka, Japan (JPHKT)',
  'Hakodate, Japan (JPHKD)',
  'Hamada, Japan (JPHMD)',
  'Hamamatsu, Japan (JPHMM)',
  'Hibi, Japan (JPHIB)',
  'Himeji, Japan (JPHIM)',
  'Hiroshima, Japan (JPHIJ)',
  'Hitachi, Japan (JPHTC)',
  'Hitachinaka, Japan (JPHIC)',
  'Hososhima, Japan (JPHSM)',
  'Imabari, Japan (JPIMB)',
  'Imari, Japan (JPIMI)',
  'Isa, Japan (JPISS)',
  'Ishigaki, Japan (JPISG)',
  'Ishikari, Japan (JPISI)',
  'Ishinomaki, Japan (JPISM)',
  'Iwakuni, Japan (JPIWK)',
  'Iyomishima, Japan (JPIYM)',
  'Kagoshima, Japan (JPKOJ)',
  'Kakogawa, Japan (JPKGA)',
  'Kanazawa, Japan (JPKNZ)',
  'Kanda, Japan (JPKND)',
  'Kashima, Japan (JPKSM)',
  'Kawasaki, Japan (JPKWS)',
  'Kinuura, Japan (JPKNU)',
  'Kisarazu, Japan (JPKZU)',
  'Kobe, Japan (JPUKB)',
  'Kochi, Japan (JPKCZ)',
  'Kumamoto, Japan (JPKMJ)',
  'Kure, Japan (JPKRE)',
  'Kushiro, Japan (JPKUH)',
  'Maizuru, Japan (JPMAI)',
  'Matsuyama, Japan (JPMYJ)',
  'Miike, Fukuoka, Japan (JPMII)',
  'Moji/Kitakyushu, Japan (JPMOJ)',
  'Muroran, Japan (JPMUR)',
  'Nagasaki, Japan (JPNGS)',
  'Nagoya, Aichi, Japan (JPNGO)',
  'Naha, Okinawa, Japan (JPNAH)',
  'Nakanoseki, Japan (JPNAN)',
  'Naoetsu, Japan (JPNAO)',
  'Naoshima, Japan (JPNAS)',
  'Niigata, Japan (JPKIJ)',
  'Niihama, Japan (JPIHA)',
  'Oita, Japan (JPOIT)',
  'Okinawa, Japan (JPOKA)',
  'Omaezaki, Japan (JPOMZ)',
  'Onahama, Japan (JPONA)',
  'Onomichi, Japan (JPONO)',
  'Osaka, Japan (JPOSA)',
  'Otake, Japan (JPOTK)',
  'Saganoseki, Japan (JPSAG)',
  'Sakaide, Japan (JPSKD)',
  'Sakaiminato, Japan (JPSMN)',
  'Sakata, Japan (JPSKT)',
  'Satsumasendai, Japan (JPSEN)',
  'Sendai, Japan (JPSDJ)',
  'Sendaishinko, Japan (JPSDS)',
  'Shibushi, Japan (JPSBS)',
  'Shikama, Japan (JPSKM)',
  'Shimizu, Japan (JPSMZ)',
  'Shimonoseki, Japan (JPSHS)',
  'Sodegaura, Japan (JPSDU)',
  'Souma, Japan (JPSMA)',
  'Tagonoura, Japan (JPTGO)',
  'Takamatsu, Japan (JPTAK)',
  'Tobata/Kitakyushu, Japan (JPTBT)',
  'Tokachi, Japan (JPTOK)',
  'Tokushima, Japan (JPTKS)',
  'Tokuyama, Japan (JPTKY)',
  'Tokyo, Japan (JPTYO)',
  'Tomakomai, Japan (JPTMK)',
  'Tonda, Japan (JPTND)',
  'Toyama, Japan (JPTOY)',
  'Toyamashinko, Japan (JPTOS)',
  'Toyohashi, Japan (JPTHS)',
  'Tsukumi, Japan (JPTMI)',
  'Tsuruga, Japan (JPTRG)',
  'Ube, Japan (JPUBJ)',
  'Unten, Japan (JPUNT)',
  'Wakayama, Japan (JPWAK)',
  'Yatsushiro, Japan (JPYAT)',
  'Yawata/Kitakyushu, Japan (JPYWT)',
  'Yokkaichi, Japan (JPYKK)',
  'Yokohama, Japan (JPYOK)',
  'Yokosuka, Japan (JPYOS)',
  'Al Aqabah, Jordan (JOAQJ)',
  'Mombasa, Kenya (KEMBA)',
  'Nairobi, Kenya (KENBO)',
  'Tarawa, Kiribati (KITRW)',
  'Kuwait, Kuwait (KWKWI)',
  'Shuaiba, Kuwait (KWSAA)',
  'Shuwaikh, Kuwait (KWSWK)',
  'Aizkraukle, Latvia (LVAIZ)',
  'Riga, Latvia (LVRIX)',
  'Salacgriva, Latvia (LVSAL)',
  'Ventspils, Latvia (LVVNT)',
  'Beirut, Lebanon (LBBEY)',
  'Tripoli, Lebanon (LBKYE)',
  'Monrovia, Liberia (LRMLW)',
  'Al Khums, Libya (LYKHO)',
  'Bingazi (Benghazi), Libya (LYBEN)',
  'Misurata, Libya (LYMRA)',
  'Tripoli, Libya (LYTIP)',
  'Klaipeda, Lithuania (LTKLJ)',
  'Antsiranana, Madagascar (MGDIE)',
  'Ehoala, Madagascar (MGEHL)',
  'Majunga (Mahajanga), Madagascar (MGMJN)',
  'Nosy-Be, Madagascar (MGNOS)',
  'Tamatave (Toamasina), Madagascar (MGTMM)',
  'Toamasina, Madagascar (MGTOA)',
  'Tulear (Toliara), Madagascar (MGTLE)',
  'Blantyre, Malawi (MWBLZ)',
  'Bagan Luar (Butterworth), Malaysia (MYBWH)',
  'Bintulu, Malaysia (MYBTU)',
  'Johor Bahru, Malaysia (MYJHB)',
  'Kota Kinabalu, Malaysia (MYBKI)',
  'Kuala Terengganu, Malaysia (MYTGG)',
  'Kuantan (Tanjong Gelang), Malaysia (MYKUA)',
  'Kuching, Malaysia (MYKCH)',
  'Labuan, Sabah, Malaysia (MYLBU)',
  'Malacca, Malaysia (MYMKZ)',
  'Mersing, Malaysia (MYMEP)',
  'Miri, Sarawak, Malaysia (MYMYY)',
  'Muar, Malaysia (MYMUA)',
  'Pasir Gudang, Malaysia (MYPGU)',
  'Penang (Georgetown), Malaysia (MYPEN)',
  'Port Klang (Pelabuhan Klang), Malaysia (MYPKG)',
  'Sandakan, Sabah, Malaysia (MYSDK)',
  'Sibu, Malaysia (MYSBW)',
  'Tanjong Baran, Malaysia (MYTBA)',
  'Tanjung Pelepas, Malaysia (MYTPP)',
  'Tawau, Malaysia (MYTWU)',
  'Westport/Port Klang, Malaysia (MYWSP)',
  'Male, Maldives (MVMLE)',
  'Bamako, Mali (MLBKO)',
  'Marsaxlokk, Malta (MTMAR)',
  'Mgarr, Gozo, Malta (MTMGZ)',
  'Valletta, Malta (MTMLA)',
  'Majuro, Marshall Islands (MHMAJ)',
  'Fort-de-France, Martinique (MQFDF)',
  'Nouadhibou, Mauritania (MRNDB)',
  'Nouakchott, Mauritania (MRNKC)',
  'Port Louis, Mauritius (MUPLU)',
  'Longoni, Mayotte (YTLON)',
  'Acapulco, Mexico (MXACA)',
  'Altamira, Mexico (MXATM)',
  'Ciudad de Mexico, Mexico (MXMEX)',
  'Coatzacoalcos, Mexico (MXCOA)',
  'Ensenada, Mexico (MXESE)',
  'Guaymas, Mexico (MXGYM)',
  'Manzanillo, Mexico (MXZLO)',
  'Progreso, Mexico (MXPGO)',
  'Puerto Morelos, Mexico (MXPMS)',
  'Reynosa, Mexico (MXREX)',
  'Salina Cruz, Mexico (MXSCX)',
  'Tampico, Mexico (MXTAM)',
  'Topolobampo, Mexico (MXTPB)',
  'Veracruz, Mexico (MXVER)',
  'Pohnpei (ex Ponape), Micronesia (FMPNI)',
  'Giurgiulesti, Moldova (MDGIU)',
  'Monaco, Monaco (MCMON)',
  'Bar, Montenegro (MEBAR)',
  'Casablanca, Morocco (MACAS)',
  'El Jadida, Morocco (MAELJ)',
  'Kenitra, Morocco (MANNA)',
  'Mohammedia, Morocco (MAMOH)',
  'Safi, Morocco (MASFI)',
  'Tanger Med, Morocco (MAPTM)',
  'Tangier, Morocco (MATNG)',
  'Beira, Mozambique (MZBEW)',
  'Maputo, Mozambique (MZMPM)',
  'Nacala, Mozambique (MZMNC)',
  'Pemba, Mozambique (MZPOL)',
  'Quelimane, Mozambique (MZUEL)',
  'Yangon, Myanmar (MMRGN)',
  'Luderitz, Namibia (NALUD)',
  'Walvis Bay, Namibia (NAWVB)',
  'Alkmaar, Netherlands (NLALK)',
  'Amsterdam, Netherlands (NLAMS)',
  'Bergen op Zoom, Netherlands (NLBZM)',
  'Dordrecht, Netherlands (NLDOR)',
  'Eemshaven, Netherlands (NLEEM)',
  'Groningen, Netherlands (NLGRQ)',
  'Hoek van Holland, Netherlands (NLHVH)',
  'IJmuiden/Velsen, Netherlands (NLIJM)',
  'Moerdijk, Netherlands (NLMOE)',
  'Rotterdam, Netherlands (NLRTM)',
  'Terneuzen, Netherlands (NLTNZ)',
  'Velsen, Netherlands (NLVEL)',
  'Vlaardingen, Netherlands (NLVLA)',
  'Vlissingen, Netherlands (NLVLI)',
  'Zaandam, Netherlands (NLZAA)',
  'Zeewolde, Netherlands (NLZEW)',
  'Bonaire, Netherlands Antilles (ANBON)',
  'Curacao, Netherlands Antilles (ANCUR)',
  'Philipsburg, Netherlands Antilles (ANPHI)',
  'St Maarten, Netherlands Antilles (ANSXM)',
  'Willemstad, Netherlands Antilles (ANWIL)',
  'Noumea, New Caledonia (NCNOU)',
  'Auckland, New Zealand (NZAKL)',
  'Bluff, New Zealand (NZBLU)',
  'Christchurch, New Zealand (NZCHC)',
  'Dunedin, New Zealand (NZDUD)',
  'Hamilton, New Zealand (NZHLZ)',
  'Lyttelton, New Zealand (NZLYT)',
  'Middleton/Christchurch, New Zealand (NZMNR)',
  'Napier, New Zealand (NZNPE)',
  'Nelson, New Zealand (NZNSN)',
  'New Plymouth, New Zealand (NZNPL)',
  'Palmerston North, New Zealand (NZPMR)',
  'Port Chalmers, New Zealand (NZPOE)',
  'Tauranga, New Zealand (NZTRG)',
  'Temuka, New Zealand (NZTKA)',
  'Timaru, New Zealand (NZTIU)',
  'Wanganui, New Zealand (NZWAG)',
  'Wellington, New Zealand (NZWLG)',
  'Whangarei, New Zealand (NZWRE)',
  'Corinto, Nicaragua (NICIO)',
  'Managua, Nicaragua (NIMGA)',
  'Apapa, Nigeria (NGAPP)',
  'Calabar, Nigeria (NGCBQ)',
  'Lagos, Nigeria (NGLOS)',
  'Onne, Nigeria (NGONN)',
  'Port Harcourt, Nigeria (NGPHC)',
  'Tincan/Lagos, Nigeria (NGTIN)',
  'Warri, Nigeria (NGWAR)',
  'Chongjin, North Korea (KPCHO)',
  'Wonsan, North Korea (KPWON)',
  'Saipan, Northern Mariana Islands (MPSPN)',
  'Agotnes, Norway (NOAGO)',
  'Alesund, Norway (NOAES)',
  'Alvik, Norway (NOAAV)',
  'Andalsnes, Norway (NOAND)',
  'Austevoll, Norway (NOASV)',
  'Bergen, Norway (NOBGO)',
  'Bodo, Norway (NOBOO)',
  'Brevik, Norway (NOBVK)',
  'Drammen, Norway (NODRM)',
  'Eigersund, Norway (NOEGD)',
  'Floro, Norway (NOFRO)',
  'Fredrikstad, Norway (NOFRK)',
  'Frekhaug, Norway (NOFKG)',
  'Fusa, Norway (NOFUS)',
  'Gjemnes, Norway (NOGJM)',
  'Halden, Norway (NOHAL)',
  'Hareid, Norway (NOHRI)',
  'Haugesund, Norway (NOHAU)',
  'Havik, Norway (NOHVI)',
  'Heroya, Norway (NOHRY)',
  'Hestvika, Norway (NOHES)',
  'Hogset, Norway (NOHOG)',
  'Holla, Norway (NOHLA)',
  'Husnes, Norway (NOHUS)',
  'Husoy - Tonsberg, Norway (NOHOY)',
  'Ikornnes, Norway (NOIKR)',
  'Karmoy, Norway (NOKMY)',
  'Knarrevik, Norway (NOKRV)',
  'Kristiansand, Norway (NOKRS)',
  'Kristiansund, Norway (NOKSU)',
  'Larvik, Norway (NOLAR)',
  'Lyngdal, Norway (NOLND)',
  'Maloy, Norway (NOMAY)',
  'Mo i Rana, Norway (NOMQN)',
  'Molde, Norway (NOMOL)',
  'Mongstad, Norway (NOMON)',
  'Moss, Norway (NOMSS)',
  'Odda, Norway (NOODD)',
  'Orkanger, Norway (NOORK)',
  'Oslo, Norway (NOOSL)',
  'Porsgrunn, Norway (NOPOR)',
  'Sandefjord, Norway (NOSAD)',
  'Sarpsborg, Norway (NOSPG)',
  'Sauda, Norway (NOSAU)',
  'Skien, Norway (NOSKE)',
  'Skogn, Norway (NOSKX)',
  'Sortland, Norway (NOSLX)',
  'Stavanger, Norway (NOSVG)',
  'Stord, Norway (NOSRP)',
  'Straumen, Norway (NOSTM)',
  'Sunndalsora, Norway (NOSUN)',
  'Svelgen, Norway (NOSVE)',
  'Tananger, Norway (NOTAE)',
  'Tonsberg, Norway (NOTON)',
  'Tromso, Norway (NOTOS)',
  'Trondheim, Norway (NOTRD)',
  'Mina\' Qabus, Oman (OMMNQ)',
  'Muscat, Oman (OMMCT)',
  'Port Qaboos, Oman (OMOPQ)',
  'Salalah, Oman (OMSLL)',
  'Sohar, Oman (OMSOH)',
  'Karachi, Pakistan (PKKHI)',
  'Karachi-muhammad Bin Qasim, Pakistan (PKBQM)',
  'Balboa, Panama (PABLB)',
  'Canazas, Panama (PACZZ)',
  'Chitre, Panama (PACTD)',
  'Coco Solo, Panama (PACSO)',
  'Colon Free Zone, Panama (PACFZ)',
  'Colon, Panama (PAONX)',
  'Cristobal, Panama (PACTB)',
  'Manzanillo, Panama (PAMIT)',
  'Panama, Panama (PAPTY)',
  'Puerto Armuelles, Panama (PAAML)',
  'Rodman, Panama (PAPSA)',
  'Lae, Papua New Guinea (PGLAE)',
  'Madang, Papua New Guinea (PGMAG)',
  'Port Moresby, Papua New Guinea (PGPOM)',
  'Rabaul, Papua New Guinea (PGRAB)',
  'Asuncion, Paraguay (PYASU)',
  'Barrio Caacupe Mi, Paraguay (PYBCM)',
  'Fenix, Paraguay (PYFNX)',
  'Pilar, Paraguay (PYPIL)',
  'Pto Seguro/col Mariano Roque Alonso, Paraguay (PYPSE)',
  'San Antonio, Paraguay (PYSAN)',
  'Terport (San Antonio), Paraguay (PYTER)',
  'Atico, Peru (PEATI)',
  'Callao, Peru (PECLL)',
  'Chimbote, Peru (PECHM)',
  'General San Martin, Peru (PEGSM)',
  'Huacho, Peru (PEHCO)',
  'Ilo, Peru (PEILQ)',
  'Iquitos, Peru (PEIQT)',
  'Lobitos, Peru (PELOB)',
  'Matarani, Peru (PEMRI)',
  'Pacasmayo, Peru (PEPAC)',
  'Paita, Peru (PEPAI)',
  'Pisco, Peru (PEPIO)',
  'Puerto Chicama, Peru (PEPCH)',
  'Salaverry, Peru (PESVY)',
  'San Nicolas, Peru (PESNX)',
  'Supe, Peru (PESUP)',
  'Talara, Peru (PETYL)',
  'Cagayan de Oro, Philippines (PHCGY)',
  'Cebu, Philippines (PHCEB)',
  'Davao, Philippines (PHDVO)',
  'General Santos, Philippines (PHGES)',
  'Iligan, Philippines (PHIGN)',
  'Isabela (Basilan), Philippines (PHISB)',
  'Manicani, Philippines (PHMNI)',
  'Manila, Philippines (PHMNL)',
  'Ozamis, Mindanao, Philippines (PHOZC)',
  'Pasaleng, Philippines (PHPSL)',
  'Zamboanga, Philippines (PHZAM)',
  'Gdansk, Poland (PLGDN)',
  'Gdynia, Poland (PLGDY)',
  'Swinoujscie, Poland (PLSWI)',
  'Szczecin, Poland (PLSZZ)',
  'Angra do Heroismo, Portugal (PTADH)',
  'Canical, Portugal (PTCNL)',
  'Entroncamento, Portugal (PTENT)',
  'Figueira da Foz, Portugal (PTFDF)',
  'Funchal, Portugal (PTFNC)',
  'Horta, Portugal (PTHOR)',
  'Leixoes, Portugal (PTLEI)',
  'Lisboa, Portugal (PTLIS)',
  'Ponta Delgada, Portugal (PTPDL)',
  'Porto, Portugal (PTOPO)',
  'Praia da Vitoria, Portugal (PTPRV)',
  'Setubal, Portugal (PTSET)',
  'Sines, Portugal (PTSIE)',
  'Terceira Island, Portugal (PTTER)',
  'Viana do Castelo, Portugal (PTVDC)',
  'Aguadilla, Puerto Rico (PRBQN)',
  'Mayaguez, Puerto Rico (PRMAZ)',
  'Ponce, Puerto Rico (PRPSE)',
  'Puerto Nuevo, Puerto Rico (PRPNU)',
  'San Juan, Puerto Rico (PRSJU)',
  'Doha, Qatar (QADOH)',
  'Mesaieed, Qatar (QAMES)',
  'Umm Sa\'id (Mesaieed), Qatar (QAUMS)',
  'Pointe Noire, Republic Of The Congo (CGPNR)',
  'Le, Reunion (RELPT)',
  'Port de Pointe des Galets, Reunion (REPDG)',
  'Reunion, Reunion (REREU)',
  'Saint-Denis de la Reunion, Reunion (RERUN)',
  'Agigea, Romania (ROAGI)',
  'Braila, Romania (ROBRA)',
  'Constanta, Romania (ROCND)',
  'Galati, Romania (ROGAL)',
  'Mangalia, Romania (ROMAG)',
  'Arkhangelsk, Russia (RUARH)',
  'Kaliningrad, Russia (RUKGD)',
  'Kholmsk, Russia (RUKHO)',
  'Korsakov, Russia (RUKOR)',
  'Krasnodar, Russia (RUKRR)',
  'Magadan, Russia (RUGDX)',
  'Murmansk, Russia (RUMMK)',
  'Nakhodka, Russia (RUNJK)',
  'Novorossiysk, Russia (RUNVS)',
  'Potapova, Russia (RUPTP)',
  'Rostov, Russia (RUROV)',
  'Saint Petersburg (ex Leningrad), Russia (RULED)',
  'Taganrog, Russia (RUTAG)',
  'Vladivostok, Russia (RUVVO)',
  'Vostochnyy, Russia (RUVYP)',
  'Vyborg, Russia (RUVYG)',
  'Kigali, Rwanda (RWKGL)',
  'Sint Eustatius (Antilles), Saint Eustatius (ANEUX)',
  'Basseterre, Saint Kitts and Nevis (KNBAS)',
  'Nevis, Saint Kitts and Nevis (KNNEV)',
  'Castries, Saint Lucia (LCCAS)',
  'Saint Lucia, Saint Lucia (LCSLU)',
  'Vieux Fort, Saint Lucia (LCVIF)',
  'Kingstown, Saint Vincent and the Grenadines (VCKTN)',
  'Apia, Samoa (WSAPW)',
  'Sao Tome Island, Sao Tome and Principe (STTMS)',
  'Ad Dammam, Saudi Arabia (SADMM)',
  'Dammam, Saudi Arabia (SADMN)',
  'Jeddah, Saudi Arabia (SAJED)',
  'Jubail, Saudi Arabia (SAJUB)',
  'King Abdullah City, Saudi Arabia (SAKAC)',
  'Riyadh, Saudi Arabia (SARUH)',
  'Dakar, Senegal (SNDKR)',
  'Mahe, Seychelles (SCMAW)',
  'Port Victoria, Seychelles (SCPOV)',
  'Freetown, Sierra Leone (SLFNA)',
  'Jurong/Singapore, Singapore (SGJUR)',
  'Singapore, Singapore (SGSIN)',
  'Bratislava, Slovakia (SKBTS)',
  'Koper, Slovenia (SIKOP)',
  'Honiara, Solomon Islands (SBHIR)',
  'Noro, New Georgia, Solomon Islands (SBNOR)',
  'Berbera, Somalia (SOBBO)',
  'Kismayu, Somalia (SOKMU)',
  'Mogadishu, Somalia (SOMGQ)',
  'Bloemfontein, South Africa (ZABFN)',
  'Cape Town, South Africa (ZACPT)',
  'Coega, South Africa (ZAZBA)',
  'Durban, South Africa (ZADUR)',
  'East London, South Africa (ZAELS)',
  'Johannesburg, South Africa (ZAJNB)',
  'Port Elizabeth, South Africa (ZAPLZ)',
  'Pretoria, South Africa (ZAPRY)',
  'Richards Bay, South Africa (ZARCB)',
  'Busan, South Korea (KRPUS)',
  'Changwon, South Korea (KRCHW)',
  'Cheonan, South Korea (KRCHO)',
  'Cheongwon-gun, South Korea (KRCWO)',
  'Chungju, South Korea (KRCHU)',
  'Daegu, South Korea (KRTAE)',
  'Daejeon, South Korea (KRTJN)',
  'Geoje, South Korea (KRJGE)',
  'Geoje, South Korea (KRKJE)',
  'Gimcheon, South Korea (KRKMC)',
  'Goyang, South Korea (KRGYG)',
  'Gumi, South Korea (KRKUM)',
  'Gunsan, South Korea (KRKUV)',
  'Gwangju, South Korea (KRKWJ)',
  'Gwangju, South Korea (KRKWU)',
  'Gwangyang, South Korea (KRKAN)',
  'Hamyang-gun, South Korea (KRHYG)',
  'Hyeonpoong/Daegu, South Korea (KRHYP)',
  'Incheon, South Korea (KRICH)',
  'Incheon, South Korea (KRINC)',
  'Janghang/Seocheon-gun, South Korea (KRCHG)',
  'Jangheung-gun, South Korea (KRJHG)',
  'Jeju, South Korea (KRCHA)',
  'Jeongeup, South Korea (KRJEO)',
  'Jinhae, South Korea (KRCHF)',
  'Jinju, South Korea (KRHIN)',
  'Masan, South Korea (KRMAS)',
  'Mokpo, South Korea (KRMOK)',
  'Namyang/Goheung-gun, South Korea (KRNYJ)',
  'Namyangju, South Korea (KRNYU)',
  'Okpo/Geoje, South Korea (KROKP)',
  'Onsan/Ulsan, South Korea (KRONS)',
  'Pohang, South Korea (KRKPO)',
  'Samcheonpo/Sacheon, South Korea (KRSCP)',
  'Seosan, South Korea (KRSSA)',
  'Seoul, South Korea (KRSEL)',
  'Tongyeong, South Korea (KRTYG)',
  'Ulsan, South Korea (KRUSN)',
  'Yeosu, South Korea (KRYOS)',
  'Yesan, South Korea (KRYES)',
  'Algeciras, Spain (ESALG)',
  'Alicante, Spain (ESALC)',
  'Almeria, Spain (ESLEI)',
  'Aviles, Spain (ESAVS)',
  'Barcelona, Spain (ESBCN)',
  'Bermeo, Spain (ESBRM)',
  'Bilbao, Spain (ESBIO)',
  'Cadiz, Spain (ESCAD)',
  'Cartagena, Spain (ESCAR)',
  'Castellon de la Plana, Spain (ESCAS)',
  'Ceuta, Spain (ESCEU)',
  'Ferez, Spain (ESFER)',
  'Gijon, Spain (ESGIJ)',
  'Huelva, Spain (ESHUV)',
  'Ibiza, Spain (ESIBZ)',
  'La Coruna (A Coruna), Spain (ESLCG)',
  'Lanzarote, Spain (ESACE)',
  'Las Palmas de Gran Canaria, Spain (ESLPA)',
  'Madrid, Spain (ESMAD)',
  'Mahon, Menorca, Spain (ESMAH)',
  'Malaga, Spain (ESAGP)',
  'Marin, Pontevedra, Spain (ESMPG)',
  'Melilla, Spain (ESMLN)',
  'Motril, Spain (ESMOT)',
  'Palamos, Spain (ESPAL)',
  'Palma de Mallorca, Spain (ESPMI)',
  'Pasajes, Spain (ESPAS)',
  'Puerto del Rosario-Fuerteventura, Spain (ESFUE)',
  'Santa Cruz de La Palma, Spain (ESSPC)',
  'Santa Cruz de Tenerife, Spain (ESSCT)',
  'Santander, Spain (ESSDR)',
  'Santurce, Spain (ESSNR)',
  'Sevilla, Spain (ESSVQ)',
  'Tabuenca, Spain (ESTBZ)',
  'Tarragona, Spain (ESTAR)',
  'Tenerife, Spain (ESTCI)',
  'Tortosa, Spain (ESTOT)',
  'Valencia, Spain (ESVLC)',
  'Vigo, Spain (ESVGO)',
  'Zaragoza, Spain (ESZAZ)',
  'Colombo, Sri Lanka (LKCMB)',
  'Port Sudan, Sudan (SDPZU)',
  'Paramaribo, Suriname (SRPBM)',
  'Ahus, Sweden (SEAHU)',
  'Falkenberg, Sweden (SEFAG)',
  'Gavle, Sweden (SEGVX)',
  'Goteborg, Sweden (SEGOT)',
  'Halmstad, Sweden (SEHAD)',
  'Helsingborg, Sweden (SEHEL)',
  'Karlshamn, Sweden (SEKAN)',
  'Karlstad, Sweden (SEKSD)',
  'Landskrona, Sweden (SELAA)',
  'Malmo, Sweden (SEMMA)',
  'Norrkoping, Sweden (SENRK)',
  'Oskarshamn, Sweden (SEOSK)',
  'Oxelosund, Sweden (SEOXE)',
  'Skelleftea, Sweden (SESFT)',
  'Skelleftehamn, Sweden (SESKE)',
  'Sodertalje, Sweden (SESOE)',
  'Stockholm, Sweden (SESTO)',
  'Sundsvall, Sweden (SESDL)',
  'Trelleborg, Sweden (SETRG)',
  'Uddevalla, Sweden (SEUDD)',
  'Umea, Sweden (SEUME)',
  'Vasteras, Sweden (SEVST)',
  'Damascus (Damas), Syria (SYDAM)',
  'Latakia, Syria (SYLTK)',
  'Tartus, Syria (SYTTS)',
  'Kaohsiung, Taiwan (TWKHH)',
  'Keelung (Chilung), Taiwan (TWKEL)',
  'Mai-liao, Taiwan (TWMLI)',
  'Suao, Taiwan (TWSUO)',
  'Taichung, Taiwan (TWTXG)',
  'Taipei, Taiwan (TWTPE)',
  'Taoyuan, Taiwan (TWTYN)',
  'Dar es Salaam, Tanzania (TZDAR)',
  'Tanga, Tanzania (TZTGT)',
  'Zanzibar, Tanzania (TZZNZ)',
  'Bangkok Modern Terminals/Bangkok, Thailand (THBMT)',
  'Bangkok, Thailand (THBKK)',
  'Bangpakong, Thailand (THBGP)',
  'Khlong Toei, Thailand (THKTY)',
  'Laem Chabang, Thailand (THLCH)',
  'Lat Krabang, Thailand (THLKR)',
  'Mab Tapud, Thailand (THMAT)',
  'Paknam, Thailand (THPKN)',
  'Pat Bangkok, Thailand (THPAT)',
  'Samut Prakarn, Thailand (THSPR)',
  'Siam Bangkok, Thailand (THSBP)',
  'Songkhla, Thailand (THSGZ)',
  'Sriracha, Thailand (THSRI)',
  'Lome, Togo (TGLFW)',
  'Nuku\'alofa, Tonga (TOTBU)',
  'Point Lisas, Trinidad and Tobago (TTPTS)',
  'Pointe a Pierre, Trinidad and Tobago (TTPTP)',
  'Port-of-Spain, Trinidad and Tobago (TTPOS)',
  'San Fernando, Trinidad and Tobago (TTSFE)',
  'Gabes, Tunisia (TNGAE)',
  'Jarjis, Tunisia (TNJAR)',
  'La Goulette Nord (Halqueloued), Tunisia (TNLGN)',
  'Rades, Tunisia (TNRDS)',
  'Sfax, Tunisia (TNSFA)',
  'Sousse, Tunisia (TNSUS)',
  'Tunis, Tunisia (TNTUN)',
  'Aliaga, Turkey (TRALI)',
  'Ambarli, Turkey (TRAMB)',
  'Antalya, Turkey (TRAYT)',
  'Avcilar, Turkey (TRAVC)',
  'Bandirma, Turkey (TRBDM)',
  'Bayrampasa, Turkey (TRBAY)',
  'Evyap Port /Kocaeli, Turkey (TREYP)',
  'Gebze, Turkey (TRGEB)',
  'Gemlik, Turkey (TRGEM)',
  'Haydarpasa, Turkey (TRHAY)',
  'Hereke, Turkey (TRHER)',
  'Iskenderun, Turkey (TRISK)',
  'Istanbul, Turkey (TRIST)',
  'Izmir, Turkey (TRIZM)',
  'Izmit, Turkey (TRIZT)',
  'Kumport, Turkey (TRKMX)',
  'Mardas, Turkey (TRMAD)',
  'Marmara Ereglisi, Turkey (TRMAR)',
  'Mersin, Turkey (TRMER)',
  'Nemrut Bay, Turkey (TRNEM)',
  'Samsun, Turkey (TRSSX)',
  'Tekirdag, Turkey (TRTEK)',
  'Trabzon, Turkey (TRTZX)',
  'Yarimca, Turkey (TRYAR)',
  'Providenciales, Turks and Caicos Islands (TCPLS)',
  'Charlotte Amalie, U.S. Virgin Islands (VICHA)',
  'Christiansted, U.S. Virgin Islands (VICTD)',
  'Saint Croix, U.S. Virgin Islands (VISTX)',
  'Saint Thomas, U.S. Virgin Islands (VISTT)',
  'Jinja, Uganda (UGJIN)',
  'Kampala, Uganda (UGKLA)',
  'Illichivs\'k, Ukraine (UAILK)',
  'Kherson, Ukraine (UAKHE)',
  'Kiev, Ukraine (UAIEV)',
  'Mariupol, Ukraine (UAMPW)',
  'Odessa, Ukraine (UAODS)',
  'Sevastopol, Ukraine (UASVP)',
  'Abu Dhabi, United Arab Emirates (AEAUH)',
  'Ajman, United Arab Emirates (AEAJM)',
  'Al Fujayrah, United Arab Emirates (AEFJR)',
  'Ar Ruways, United Arab Emirates (AERUW)',
  'Dubai, United Arab Emirates (AEDXB)',
  'Jebel Ali, United Arab Emirates (AEJEA)',
  'Jebel Dhanna, United Arab Emirates (AEJED)',
  'Khor al Fakkan, United Arab Emirates (AEKLF)',
  'Port Rashid, United Arab Emirates (AEPRA)',
  'Ras al Khaimah, United Arab Emirates (AERKT)',
  'Sharjah, United Arab Emirates (AESHJ)',
  'Widnes, United Kingdom (GBWDN)',
  'Umm al Qaiwain, United Arab Emirates (AEQIW)',
  'Aberdeen, United Kingdom (GBABD)',
  'Avonmouth, United Kingdom (GBAVO)',
  'Barry Dock, United Kingdom (GBBAD)',
  'Belfast, United Kingdom (GBBEL)',
  'Birkenhead, United Kingdom (GBBRK)',
  'Bootle, United Kingdom (GBBOE)',
  'Boston, United Kingdom (GBBOS)',
  'Bridgwater, United Kingdom (GBBRW)',
  'Bridlington, United Kingdom (GBBRT)',
  'Bristol, United Kingdom (GBBRS)',
  'Broadstairs, United Kingdom (GBBDT)',
  'Burnham on Crouch, United Kingdom (GBBOC)',
  'Cairnryan, United Kingdom (GBCYN)',
  'Cardiff, United Kingdom (GBCDF)',
  'Carrickfergus, United Kingdom (GBCFG)',
  'Charleston, United Kingdom (GBCHD)',
  'Dover, United Kingdom (GBDVR)',
  'Dundee, United Kingdom (GBDUN)',
  'Edinburgh, United Kingdom (GBEDI)',
  'Ellesmere, United Kingdom (GBELL)',
  'Falmouth, United Kingdom (GBFAL)',
  'Fawley, United Kingdom (GBFAW)',
  'Felixstowe, United Kingdom (GBFXT)',
  'Fraserburgh, United Kingdom (GBFRB)',
  'Glasgow, United Kingdom (GBGLW)',
  'Goole, United Kingdom (GBGOO)',
  'Grangemouth, United Kingdom (GBGRG)',
  'Gravesend, United Kingdom (GBGVS)',
  'Great Yarmouth, United Kingdom (GBGTY)',
  'Greenock, United Kingdom (GBGRK)',
  'Grimsby, United Kingdom (GBGSY)',
  'Harwich, United Kingdom (GBHRW)',
  'Hull, United Kingdom (GBHUL)',
  'Immingham, United Kingdom (GBIMM)',
  'Inverkeithing, United Kingdom (GBINK)',
  'Inverness, United Kingdom (GBINV)',
  'Ipswich, United Kingdom (GBIPS)',
  'Irlam, United Kingdom (GBIRL)',
  'King\'s Lynn, United Kingdom (GBKLN)',
  'Lancaster, United Kingdom (GBLAN)',
  'Liverpool, United Kingdom (GBLIV)',
  'London Gateway, United Kingdom (GBLGP)',
  'London, United Kingdom (GBLON)',
  'Macduff, United Kingdom (GBMCD)',
  'Maldon, United Kingdom (GBMAL)',
  'Maryport, United Kingdom (GBMRY)',
  'Middlesbrough, United Kingdom (GBMID)',
  'Moaness, Hoy, United Kingdom (GBMNS)',
  'Montrose, United Kingdom (GBMON)',
  'Nelson, United Kingdom (GBNLN)',
  'Newcastle upon Tyne, United Kingdom (GBNCL)',
  'Newhaven, United Kingdom (GBNHV)',
  'Newport, United Kingdom (GBNPT)',
  'Northfleet, United Kingdom (GBNFT)',
  'Parkeston Quay, United Kingdom (GBPST)',
  'Pen-Clawdd, United Kingdom (GBPDD)',
  'Plymouth, United Kingdom (GBPLY)',
  'Poole, United Kingdom (GBPOO)',
  'Portbury, United Kingdom (GBPRU)',
  'Portsmouth, United Kingdom (GBPME)',
  'Preston, United Kingdom (GBPRE)',
  'Purfleet, United Kingdom (GBPFT)',
  'Queenborough, United Kingdom (GBQUB)',
  'Rye, United Kingdom (GBRYE)',
  'Scarborough, United Kingdom (GBSCA)',
  'Seaton, United Kingdom (GBEON)',
  'Sheerness, United Kingdom (GBSHS)',
  'Silvertown, United Kingdom (GBSVT)',
  'South Shields, United Kingdom (GBSSH)',
  'Southampton, United Kingdom (GBSOU)',
  'Stanlow, United Kingdom (GBSOW)',
  'Stonehouse, United Kingdom (GBYVZ)',
  'Sunderland, United Kingdom (GBSUN)',
  'Swansea, United Kingdom (GBSWA)',
  'Teesport, United Kingdom (GBTEE)',
  'Thamesport, United Kingdom (GBTHP)',
  'Tilbury, United Kingdom (GBTIL)',
  'Tyne, United Kingdom (GBTYN)',
  'Workington, United Kingdom (GBWOR)',
  'Anchorage, United States (USANC)',
  'Annapolis, United States (USANP)',
  'Atlanta, United States (USATL)',
  'Baltimore, United States (USBAL)',
  'Bear Creek, United States (USBCC)',
  'Beaumont, United States (USBPT)',
  'Birmingham, United States (USBHM)',
  'Boston, United States (USBOS)',
  'Brownsville, United States (USBRO)',
  'Brunswick, United States (USSSI)',
  'Buffalo, United States (USBUF)',
  'Cape Canaveral, United States (USCPV)',
  'Cape Romanzof, United States (USCZF)',
  'Charleston, United States (USCHS)',
  'Charlotte, United States (USCLT)',
  'Chattanooga, United States (USCHA)',
  'Chicago, United States (USCHI)',
  'Cincinnati, United States (USCVG)',
  'Cleveland, United States (USCLE)',
  'Columbus, United States (USCMH)',
  'Corpus Christi, United States (USCRP)',
  'Dallas, United States (USDAL)',
  'Dalton, United States (USDNN)',
  'Damascus, United States (USAR5)',
  'Dauphin, United States (USDA8)',
  'Decatur, United States (USDEC)',
  'Denver, United States (USDEN)',
  'Des Moines, United States (USDSM)',
  'Detroit, United States (USDET)',
  'Dutch Harbor, United States (USDUT)',
  'El Paso, United States (USELP)',
  'Fernandina Beach, United States (USFEB)',
  'Fort Lauderdale, United States (USFLL)',
  'Fort Worth, United States (USFWT)',
  'Freeport, United States (USFPO)',
  'Fresh Water Bay, United States (USFRP)',
  'Galveston, United States (USGLS)',
  'Gulfport, United States (USGPT)',
  'Hampton-Williamsburg-Newport News, United States (USPHF)',
  'Honolulu, United States (USHNL)',
  'Houston, United States (USHOU)',
  'Howard Beach/Queens/New York, United States (USXGO)',
  'Huntsville, United States (USHSV)',
  'Indianapolis, United States (USIND)',
  'Jacksonville, United States (USJ3C)',
  'Jacksonville, United States (USJAX)',
  'Joliet, United States (USJOT)',
  'Kansas City, United States (USKCK)',
  'Kansas City, United States (USMKC)',
  'Kenai, United States (USENA)',
  'Kirkland, United States (USXHF)',
  'Kodiak, United States (USADQ)',
  'Lake Charles, United States (USLCH)',
  'Laredo, United States (USLRD)',
  'Las Vegas, United States (USLAS)',
  'Long Beach, United States (USLGB)',
  'Long Island City/Queens/New York, United States (USXHO)',
  'Los Alamitos, United States (USLAT)',
  'Los Angeles, United States (USLAX)',
  'Louisville, United States (USLUI)',
  'Memphis, United States (USMEM)',
  'Miami, United States (USMIA)',
  'Milwaukee, United States (USMKE)',
  'Minneapolis, United States (USMES)',
  'Minneapolis/St Paul, United States (USMSP)',
  'Mobile, United States (USMOB)',
  'Morehead City, United States (USMRH)',
  'Nashville, United States (USBNA)',
  'New Orleans, United States (USMSY)',
  'New York, United States (USNYC)',
  'Newark, United States (USEWR)',
  'Newburgh, United States (USSWF)',
  'Newport News, United States (USNNS)',
  'Norfolk, United States (USORF)',
  'North Charleston, United States (USNTS)',
  'Oakboro, United States (USYOB)',
  'Oakland, United States (USOAK)',
  'Oceanside, United States (USOCN)',
  'Olympia, United States (USOLM)',
  'Omaha, United States (USOMA)',
  'Orlando, United States (USORL)',
  'Otay Mesa, United States (USOYM)',
  'Palm Beach, United States (USPAB)',
  'Panama City, United States (USPFN)',
  'Pascagoula, United States (USPGL)',
  'Pearson, United States (USPS6)',
  'Pennsauken, United States (USPPS)',
  'Pensacola, United States (USPNS)',
  'Peoria, United States (USPIA)',
  'Philadelphia, United States (USPHL)',
  'Phoenix, United States (USPHX)',
  'Pittsburgh, United States (USPIT)',
  'Plymouth, United States (USPYM)',
  'Port Angeles, United States (USCLM)',
  'Port Arthur, United States (USPOA)',
  'Port Canaveral, United States (USPCV)',
  'Port Chester, United States (USUXZ)',
  'Port Elizabeth, United States (USPEB)',
  'Port Everglades, United States (USPEF)',
  'Port Hueneme, United States (USNTD)',
  'Port Manatee, United States (USPME)',
  'Port Wentworth, United States (USPWN)',
  'Portage Creek, United States (USPCA)',
  'Portland, United States (USPDX)',
  'Portland, United States (USPWM)',
  'Portsmouth, United States (USPTM)',
  'Providence, United States (USPVD)',
  'Richmond, United States (USRIC)',
  'Riviera Beach, United States (USRBC)',
  'Rotterdam, United States (USRAJ)',
  'Sacramento, United States (USSAC)',
  'Saint Louis, United States (USSTL)',
  'Saint Paul, United States (USSTP)',
  'Salt Lake City, United States (USSLC)',
  'San Diego, United States (USSAN)',
  'San Francisco, United States (USSFO)',
  'Savannah, United States (USSAV)',
  'Savannah, United States (USTSA)',
  'Seattle, United States (USSEA)',
  'South Saint Paul, United States (USSPT)',
  'Stockton, United States (USSCK)',
  'Sturgeon Bay, United States (USSUE)',
  'Superior, United States (USSUW)',
  'Swartz Creek, United States (USSXZ)',
  'Tacoma, United States (USTIW)',
  'Tamms, United States (USTMM)',
  'Tampa, United States (USTPA)',
  'Toledo, United States (USTOL)',
  'Tonawanda, United States (USUZF)',
  'Tulsa, United States (USTUL)',
  'Virginia Beach, United States (USVAB)',
  'Washington, United States (USOCW)',
  'Waukegan, United States (USUGN)',
  'Wilmington, United States (USILM)',
  'Colonia, Uruguay (UYCYR)',
  'Montevideo, Uruguay (UYMVD)',
  'Nueva Palmira, Uruguay (UYNVP)',
  'Paysandu, Uruguay (UYPDU)',
  'Espiritu Santo, Vanuatu (VUSON)',
  'Port Vila, Vanuatu (VUVLI)',
  'Amuay, Venezuela (VEAMY)',
  'Barcelona, Venezuela (VEBLA)',
  'El Guamache, Venezuela (VEEGU)',
  'El Tablazo/Maracaibo L, Venezuela (VEETV)',
  'Guanta, Venezuela (VEGUT)',
  'Guaranao Bay, Venezuela (VEGUB)',
  'La Guaira, Venezuela (VELAG)',
  'La Salina/Maracaibo L, Venezuela (VELSV)',
  'Maracaibo, Venezuela (VEMAR)',
  'Matanzas, Venezuela (VEMTV)',
  'Puerto Cabello, Venezuela (VEPBL)',
  'Puerto Ordaz, Venezuela (VEPZO)',
  'Puerto Sucre, Venezuela (VEPSU)',
  'Punta Cardon, Venezuela (VEPCN)',
  'Cai Lan, Vietnam (VNCLN)',
  'Cai Mep, Vietnam (VNTOT)',
  'Cat Lai, Vietnam (VNCLI)',
  'Da Nang, Vietnam (VNDAD)',
  'Haiphong, Vietnam (VNHPH)',
  'Ho Chi Minh City, Vietnam (VNSGN)',
  'Ho Chi Minh, Vietnam (VNVIC)',
  'Nha Trang, Vietnam (VNNHA)',
  'Phuoc Long, Vietnam (VNPHG)',
  'Qui Nhon, Vietnam (VNUIH)',
  'Su Tu Den, Vietnam (VNSTD)',
  'Tan Thuan Dong, Vietnam (VNTTD)',
  'Vung Tau, Vietnam (VNVUT)',
  'Aden, Yemen (YEADE)',
  'Hodeidah, Yemen (YEHOD)',
  'Little Aden, Yemen (YELAD)',
  'Mukalla, Yemen (YEMKX)',
  'Lusaka, Zambia (ZMLUN)',
  'Bulawayo, Zimbabwe (ZWBUQ)',
  'Harare, Zimbabwe (ZWHRE)',
  'Mutare, Zimbabwe (ZWUTA)',
];

const PORTS_DESTINATION_RAW: string[] = [
  'Aratu, Brazil (BRARB)',
  'Areia Branca, Brazil (BRARE)',
  'Belem, Brazil (BRBEL)',
  'Cabedelo, Brazil (BRCDO)',
  'Forno, Brazil (BRFNO)',
  'Fortaleza, Brazil (BRFOR)',
  'Ilheus, Brazil (BRIOS)',
  'Imbituba, Brazil (BRIBB)',
  'Itabirito, Brazil (BRIRO)',
  'Itaguai, Brazil (BRIGI)',
  'Itajai, Brazil (BRITJ)',
  'Itapemirim, Brazil (BRITZ)',
  'Itapoa, Brazil (BRIOA)',
  'Itaqui, Brazil (BRITQ)',
  'Maceio, Brazil (BRMCZ)',
  'Manaus, Brazil (BRMAO)',
  'Natal, Brazil (BRNAT)',
  'Navegantes, Brazil (BRNVT)',
  'Parana, Brazil (BRPNN)',
  'Paranagua, Brazil (BRPNG)',
  'Pecem, Brazil (BRPEC)',
  'Porto Alegre, Brazil (BRPOA)',
  'Porto de Itaguai, Brazil (BRSPB)',
  'Portocel, Brazil (BRPCL)',
  'Recife, Brazil (BRREC)',
  'Rio de Janeiro, Brazil (BRRIO)',
  'Rio Grande, Brazil (BRRIG)',
  'Salto Grande, Brazil (BRSAL)',
  'Salvador, Brazil (BRSSA)',
  'Santarem, Brazil (BRSTM)',
  'Santos, Brazil (BRSSZ)',
  'Sao Francisco do Sul, Brazil (BRSFS)',
  'Sao Sebastiao, Brazil (BRSSO)',
  'Suape, Brazil (BRSUA)',
  'Vila do Conde, Brazil (BRVIC)',
  'Vila do Conde, Brazil (BRVLC)',
  'Vitoria da Conquista, Brazil (BRVDC)',
  'Vitoria, Brazil (BRVIX)',
];

export const PORTS_DEPARTURE_OPTIONS: ComboboxOption[] = PORTS_DEPARTURE_RAW.map(
  (v) => ({ value: v, label: v }),
);

export const PORTS_DESTINATION_OPTIONS: ComboboxOption[] = PORTS_DESTINATION_RAW.map(
  (v) => ({ value: v, label: v }),
);
