"""Add quotation_client_tokens table

Revision ID: 048
Revises: 047
Create Date: 2026-05-07

Adds centrix_quotation_client_tokens to support shareable client portal links
generated by operators after proposals are received. Each token is valid for 30
days and scoped to a single quotation.
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql as pg

revision = "048"
down_revision = "047"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "centrix_quotation_client_tokens",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "quotation_id",
            pg.UUID(as_uuid=True),
            sa.ForeignKey("centrix_quotation_quotations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("token", sa.String(64), nullable=False, unique=True),
        sa.Column("created_by", sa.String, nullable=False),
        sa.Column("observations", sa.Text, nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.create_index(
        "ix_client_tokens_quotation_id",
        "centrix_quotation_client_tokens",
        ["quotation_id"],
    )
    op.create_index(
        "ix_client_tokens_token",
        "centrix_quotation_client_tokens",
        ["token"],
        unique=True,
    )


def downgrade() -> None:
    op.drop_index("ix_client_tokens_token", table_name="centrix_quotation_client_tokens")
    op.drop_index("ix_client_tokens_quotation_id", table_name="centrix_quotation_client_tokens")
    op.drop_table("centrix_quotation_client_tokens")
