const assert = require('node:assert/strict');
const M = require('../../public/prototypes/centrix-auditoria/model.js');
let count = 0;
function check(name, fn) { fn(); console.log('OK '+name); count++; }
const ops = M.seed(), op = id => ops.find(o => o.id === id);
check('cobrança correta não esconde atraso', () => { assert.equal(M.financial(op('0007')).status,'clean'); assert.equal(M.operational(op('0007')).deviations[0].actual,43); });
check('fatura ausente não bloqueia performance', () => { assert.equal(M.financial(op('0012')).status,'missing'); assert.equal(M.operational(op('0012')).complete,true); });
check('diferenças discriminadas somam 195', () => { const r=M.financial(op('0011')); assert.equal(r.totals.USD,195); assert.equal(r.cases.length,1); });
check('moedas não são somadas e desconto não compensa diferença positiva', () => { assert.deepEqual(M.financial(op('0013')).totals,{USD:180,BRL:150}); });
check('casos contam cobranças e cobertura não conta ausentes', () => { assert.deepEqual(M.summary(ops,'preco'),{totals:{USD:695,BRL:150},cases:4,checked:7,known:9}); });
check('filtros contam operações, com sobreposição explícita', () => { assert.equal(ops.filter(o=>M.matches(o,'preco','deviation')).length,3); assert.equal(ops.filter(o=>M.matches(o,'preco','missing')).length,2); });
check('cobertura parcial nunca fica conforme', () => { const r=M.financial(op('0013')); assert.equal(r.complete,false); assert.equal(r.status,'deviation'); assert.equal(M.matches(op('0013'),'preco','clean'),false); });
check('previsão revisada não é desvio realizado', () => { const r=M.operational(op('0008')); assert.equal(r.deviations.length,0); assert.equal(r.evaluated.length,0); assert.equal(r.status,'pending'); });
check('sem compromisso não usa realizado como referência', () => { const r=M.operational(op('0013')); assert.equal(r.status,'missing'); assert.equal(r.deviations.length,0); });
check('redução de free time é desvio de serviço', () => { assert.equal(M.operational(op('0010')).deviations[0].actual,14); });
check('busca ignora acentos e filtra a mesma base dos indicadores', () => { const found=M.filterOperations(ops,{query:'genova'}); assert.equal(found.length,1); assert.equal(found[0].id,'0007'); assert.equal(M.summary(found,'preco').cases,0); });
check('período é abertura, incluindo dia final', () => { const found=M.filterOperations(ops,{from:'2026-09-10',to:'2026-09-12'}); assert.deepEqual(found.map(o=>o.id).sort(),['0008','0013']); });
check('agente e fornecedor se combinam', () => assert.equal(M.filterOperations(ops,{agent:'Agente Alpha',supplier:'Eastbridge Components'}).length,2));
check('complemento financeiro não altera performance nem outra cobrança', () => { const o=M.clone(op('0013')); const before=JSON.stringify(o.checks), invoiceBefore=JSON.stringify(o.invoices[0]); M.complement(o,'preco','FAT-0013-C'); assert.equal(JSON.stringify(o.checks),before); assert.equal(JSON.stringify(o.invoices[0]),invoiceBefore); assert.equal(M.financial(o).complete,true); assert.equal(o.version,2); });
check('complemento é idempotente e preserva log anterior', () => { const o=M.clone(op('0012')); const original=M.clone(o.logs); M.complement(o,'preco'); const version=o.version; assert.equal(M.complement(o,'preco'),false); assert.equal(o.version,version); assert.deepEqual(o.logs.slice(0,original.length),original); });
check('complemento de performance não cria fatura', () => { const o=M.clone(op('0013')); M.complement(o,'performance'); assert.equal(M.financial(o).missing,1); assert.equal(M.operational(o).deviations.length,1); });
const externalInput={supplier:'Teste',bl:'EX-TEST',po:'PO-2026-084',agent:'Agente Teste',route:'A → B',scope:'both',sample:'partial'};
check('mesma PO com BL distinto é outra operação', () => { const copy=M.clone(ops); const r=M.addExternal(copy,externalInput); assert.equal(r.existing,false); assert.equal(copy.length,8); });
check('mesmo BL reabre sem duplicar ou sobrescrever', () => { const copy=M.clone(ops); const r=M.addExternal(copy,{...externalInput,bl:' '+copy[0].bl.toLowerCase()+' '}); assert.equal(r.existing,true); assert.equal(copy.length,7); assert.equal(r.op.id,'0011'); });
check('externa parcial confere performance e aguarda fatura', () => { const r=M.addExternal([],externalInput).op; assert.equal(M.financial(r).status,'missing'); assert.equal(M.operational(r).status,'deviation'); });
check('arquivo sem fonte interpretada não produz conclusão', () => { const r=M.addExternal([],{...externalInput,sample:null,filenames:['fatura.pdf']}).op; assert.equal(M.financial(r).status,'missing'); assert.equal(M.operational(r).status,'missing'); });
check('escopo exclusivo não conta como conforme na outra dimensão', () => { const r=M.addExternal([],{...externalInput,scope:'performance',sample:'ready'}).op; assert.equal(M.financial(r).status,'outside'); assert.equal(M.summary([r],'preco').known,0); });
check('performance tem cobertura e pedidos independentes do preço', () => { assert.deepEqual(M.summary(ops,'performance'),{deviations:2,cases:2,checked:5,partial:0,known:7}); });
check('entrada parcial abre a dimensão disponível', () => { const o=M.addExternal([],externalInput).op; assert.equal(M.entryDimension(o,'preco'),'performance'); });
check('escopo pendente exclusivo permanece na dimensão solicitada', () => { const o=M.addExternal([],{...externalInput,scope:'preco'}).op; assert.equal(M.entryDimension(o,'performance'),'preco'); });
check('data de abertura da trilha corresponde à operação', () => ops.forEach(o=>assert.equal(o.logs[0].date,o.opened)));
console.log(`${count} verificações aprovadas.`);
