const assert=require('node:assert/strict'),E=require('../../public/prototypes/centrix-auditoria/entry.js'),M=require('../../public/prototypes/centrix-auditoria/model.js'),F=require('../../public/prototypes/centrix-auditoria/freight.js'),P=require('../../public/prototypes/centrix-auditoria/performance.js');
const ops=P.enrich(F.enrich(M.seed()));let count=0;
function test(name,fn){fn();count++;console.log('OK '+name);}
function valid(){const d=E.fresh();Object.assign(d.fields,{supplier:'Teste DEMO',direction:'Importação',modal:'Marítimo FCL',origin:'Shanghai',destination:'Santos',incoterm:'FOB',namedPlace:'Shanghai',contractor:'Comprador / cliente',owner:'Analista demo',contextConfirmed:true});return d;}
test('busca reúne cotação, embarque e auditoria sem misturar histórico por padrão',()=>{const d=E.fresh();const a=E.search(ops,d);assert.ok(a.some(r=>r.kind==='quote'));assert.ok(a.some(r=>r.kind==='shipment'));assert.ok(a.every(r=>!r.history));d.history=true;d.query='2025';assert.equal(E.search(ops,d)[0].id,'H-DEMO-2025');});
test('cotação interna reaproveita contexto e aceite; não inventa embarque',()=>{const d=E.select(E.catalogue(ops).find(r=>r.kind==='quote'));assert.equal(d.fields.shipmentOrigin,'Ainda não registrado');assert.equal(d.fields.bl,'');assert.equal(d.fields.incoterm,'FOB');assert.equal(d.sources[0].linked,true);});
test('embarque interno mantém referência comercial externa pendente',()=>{const d=E.select(E.catalogue(ops).find(r=>r.kind==='shipment'));assert.equal(d.fields.shipmentOrigin,'Centrix');assert.equal(d.fields.quoteOrigin,'Externa');assert.equal(d.sources[0].linked,false);});
test('BL não é obrigatório em preparação e contexto continua obrigatório',()=>{const d=valid();assert.deepEqual(E.errors(d,2),[]);d.fields.contractor='';assert.ok(E.errors(d,2).length);});
test('Incoterm não altera prepaid/collect e NA exige justificativa',()=>{const d=valid();d.fields.incoterm='CIF';assert.equal(d.fields.payment,'Não confirmado');d.fields.incoterm='NA';assert.ok(E.errors(d,2).length);d.fields.absenceReason='Justificativa DEMO';assert.deepEqual(E.errors(d,2),[]);});
test('aceite declarado exige evidência, data, aprovador e fonte',()=>{const d=valid();d.fields.referenceConfirmed=true;assert.equal(E.errors(d,3).length,2);Object.assign(d.fields,{referenceApprover:'Cliente demo',referenceDate:'2026-09-10',referenceEvidence:'Email demo'});d.sources[0].files=['cotacao-demo.pdf'];assert.deepEqual(E.errors(d,3),[]);});
test('arquivo selecionado não produz extração, valores ou conformidade',()=>{const a=[],d=valid();d.sources[0].files=['documento.pdf'];d.sources[0].status='Arquivo selecionado';const {op}=E.create(a,d,'2026-09-13');P.enrich(F.enrich(a));assert.equal(op.invoices.length,0);assert.equal(M.financial(op).status,'missing');assert.equal(M.operational(op).evaluated.length,0);assert.equal(M.operational(op).status,'missing');});
test('mesmo documento recebido não cria outra operação sem revisão',()=>{const d=valid();d.fields.bl=ops[0].bl;assert.equal(E.duplicates(ops,d).length,1);const a=structuredClone(ops);assert.ok(E.create(a,d,'2026-09-13').errors.length);assert.equal(a.length,ops.length);});
test('BL compartilhado admite operação distinta com confirmação e justificativa',()=>{const d=valid();Object.assign(d.fields,{bl:ops[0].bl,distinctConfirmed:true,distinctReason:'HBL diferente; referência de consolidação compartilhada DEMO'});const a=structuredClone(ops);assert.deepEqual(E.create(a,d,'2026-09-13').errors,[]);assert.equal(a.length,ops.length+1);});
test('mesma PO em BL diferente não é duplicidade automática',()=>{const d=valid();d.fields.po=ops[0].po;d.fields.bl='OUTRO-BL-DEMO';assert.equal(E.duplicates(ops,d).length,0);});
test('histórico conserva período original e abertura da auditoria separada',()=>{const d=E.select(E.catalogue(ops).find(r=>r.kind==='history'));Object.assign(d.fields,{...valid().fields,period:'Concluída',operationDate:'2025-11-06'});const a=[];const {op}=E.create(a,d,'2026-09-13');assert.equal(op.opened,'2026-09-13');assert.equal(op.entryContext.operationDate,'2025-11-06');assert.equal(op.entryContext.period,'Concluída');assert.deepEqual(op.timeline,[]);});
test('importar a mesma fonte histórica reusa registro e não duplica',()=>{const a=[],d=valid();d.recordKey='legacy:H-DEMO-2025';E.create(a,d,'2026-09-13');const r=E.create(a,d,'2026-09-13');assert.equal(r.existing,true);assert.equal(a.length,1);});
test('complemento preserva valores, performance, versões e log anterior',()=>{const a=structuredClone(ops),o=a[0],d=E.select(E.catalogue(a).find(r=>r.op===o));Object.assign(d.fields,{owner:'Analista demo',contextConfirmed:true});const financial=structuredClone(M.financial(o)),performance=structuredClone(M.operational(o)),logs=structuredClone(o.logs);const r=E.create(a,d,'2026-09-13');assert.deepEqual(r.errors,[]);assert.equal(a.length,ops.length);assert.deepEqual(M.financial(o),financial);assert.deepEqual(M.operational(o),performance);assert.deepEqual(o.logs.slice(0,logs.length),logs);});
test('cobranças são distintas por emissor e número; duplicata gera revisão',()=>{const d=valid();d.charges=[{id:'F1',issuer:'A'},{id:'F1',issuer:'B'}];assert.equal(E.errors(d,3).length,0);d.charges.push({id:'F1',issuer:'A'});assert.ok(E.errors(d,3).length);});
test('evento informado requer fonte e continua separado da cronologia validada',()=>{const d=valid();d.events=[{name:'Chegada',kind:'Previsão revisada',date:'2026-10-01',source:''}];assert.ok(E.errors(d,3).length);d.events[0].source='Email demo';const a=[],r=E.create(a,d,'2026-09-13');assert.equal(r.op.entryEvents.length,1);assert.equal(r.op.timeline.length,0);});
test('documento indisponível ou dispensa solicitada exige motivo; não aprova dispensa',()=>{const d=valid();d.sources[1].status='Dispensa solicitada';assert.ok(E.errors(d,3).length);d.sources[1].reason='Solicitação demo';const a=[],r=E.create(a,d,'2026-09-13');assert.equal(r.op.entrySources[1].status,'Dispensa solicitada');assert.equal(r.op.entryPending,true);});
test('exigibilidade depende do contexto sem impedir outra dimensão',()=>{const d=valid();d.fields.scope='performance';assert.equal(E.requirement(d.sources.find(s=>s.id==='invoice'),d.fields),'Fora do recorte');assert.equal(E.requirement(d.sources.find(s=>s.id==='export'),d.fields),'Não aplicável');d.fields.direction='Exportação';assert.equal(E.requirement(d.sources.find(s=>s.id==='export'),d.fields),'Condicional');});
test('auditoria avulsa não gera despacho e não ganha dados falsos',()=>{const a=[],d=valid();d.fields.relation='Somente auditoria';const {op}=E.create(a,d,'2026-09-13');assert.equal(op.entryContext.relation,'Somente auditoria');assert.deepEqual(op.timeline,[]);assert.deepEqual(op.invoices,[]);assert.equal(op.external,true);});
test('ampliação do recorte preserva dimensão existente',()=>{const a=[],d=valid();d.fields.scope='preco';const {op}=E.create(a,d,'2026-09-13');d.opId=op.id;d.fields.scope='both';E.create(a,d,'2026-09-13');assert.deepEqual(op.requested,['preco','performance']);});
test('busca geral consolida fonte já vinculada; retomada conserva complemento',()=>{const a=[],d=valid();d.recordKey='quote:Q-DEMO-01';d.fields.quoteId='Q-DEMO-01 · v1';d.charges=[{id:'F-01',issuer:'Demo'}];E.create(a,d,'2026-09-13');const found=E.search(a,E.fresh());assert.equal(found.filter(r=>r.op||r.already).length,1);const resumed=E.select(E.catalogue(a).find(r=>r.key==='quote:Q-DEMO-01'));assert.equal(resumed.charges[0].id,'F-01');});
console.log(count+' verificações de entrada aprovadas.');
