const assert=require('node:assert/strict');
const F=require('../../public/prototypes/centrix-auditoria/freight.js'), M=require('../../public/prototypes/centrix-auditoria/model.js');
let n=0; const check=(name,fn)=>{fn();console.log('OK '+name);n++;};
const seeded=()=>F.enrich(M.seed());
check('PTAX aplica spread percentual, isola impacto em BRL e preserva USD',()=>{const op=seeded()[0],q=F.exchange(op,op.invoices[0]);assert.equal(q.expectedRate,5.1);assert.equal(q.base,4620);assert.equal(q.delta,462);assert.deepEqual(M.financial(op).totals,{USD:195,BRL:462});});
check('fórmula reconcilia diferença de rubricas e diferença cambial sem duplicação',()=>{const op=seeded()[0],q=F.exchange(op,op.invoices[0]);assert.equal(F.round(195*q.expectedRate+q.delta),F.round(q.billed-4425*q.expectedRate));});
check('câmbio sozinho gera caso mesmo quando todos os itens estão conformes',()=>{const op=seeded().find(o=>o.id==='0007');op.freight.fx[op.invoices[0].id].appliedRate=5.2;assert.equal(M.financial(op).cases.length,1);assert.deepEqual(M.financial(op).totals,{BRL:396});});
check('câmbio sem regra aprovada não vira leakage',()=>{const op=seeded()[0];op.freight.fx['FAT-0011'].approved=false;assert.equal(F.exchange(op,op.invoices[0]).status,'pending');assert.deepEqual(M.financial(op).totals,{USD:195});});
check('falta de data, boletim, lado ou fonte mantém inconclusivo',()=>{for(const field of ['referenceDate','bulletin','side','referenceEvidence']){const op=seeded()[0];op.freight.fx['FAT-0011'][field]=null;assert.equal(F.exchange(op,op.invoices[0]).status,'pending');}});
check('taxa da moeda errada não é comparada',()=>{const op=seeded()[0];op.freight.fx['FAT-0011'].from='EUR';assert.equal(F.exchange(op,op.invoices[0]).question,0);});
check('data diferente com taxa igual requer validação',()=>{const op=seeded().find(o=>o.id==='0007');op.freight.fx['FAT-0007'].appliedDate='2026-09-03';assert.equal(F.exchange(op,op.invoices[0]).status,'pending');});
check('spread absoluto é diferente de percentual',()=>{const op=seeded()[0];Object.assign(op.freight.fx['FAT-0011'],{spreadType:'absolute',spread:0.1});assert.equal(F.exchange(op,op.invoices[0]).expectedRate,5.1);});
check('fatura ausente não produz impacto cambial',()=>{const op=seeded()[0];op.invoices[0].available=false;assert.equal(F.exchange(op,op.invoices[0]).status,'pending');});
check('alteração válida preserva original e não gera contestação',()=>{const line={agreed:100,billed:120,tolerance:0,change:{amount:120,approved:true,approver:'Cliente',date:'2026-09-01',evidence:'Aceite',reason:'Serviço adicional solicitado'}};assert.equal(F.charge(line).status,'authorized');assert.equal(F.charge(line).question,0);assert.equal(line.agreed,100);});
check('alteração sem evidência não substitui original',()=>{const line={agreed:100,billed:120,tolerance:0,change:{amount:120,approved:true}};assert.equal(F.charge(line).expected,100);assert.equal(F.charge(line).question,20);});
check('limite de tolerância e diferença a menor não geram caso',()=>{assert.equal(F.charge({agreed:100,billed:100.01,tolerance:0.01}).status,'tolerance');assert.equal(F.charge({agreed:100,billed:99,tolerance:0}).question,0);});
check('tolerância ausente não equivale a zero',()=>assert.equal(F.charge({agreed:100,billed:120}).status,'pending'));
check('taxa não prevista tem percentual indefinido',()=>{const q=F.charge({agreed:0,billed:150,tolerance:0});assert.equal(q.percent,null);assert.equal(q.question,150);});
check('não aplicáveis são excluídos da cobertura',()=>{const c=F.coverage(seeded()[0]);assert.equal(c.known+c.na,c.items.length);assert.equal(c.checked+c.pending,c.known);});
check('histórico incompleto não afirma ausência de duplicidade',()=>{const op=seeded().find(o=>o.id==='0007');assert.equal(F.controls(op).find(c=>c.id==='duplicates').status,'pending');assert.equal(M.financial(op).complete,false);assert.equal(M.operational(op).status,'deviation');});
check('enriquecimento é idempotente e preserva demais operações e logs',()=>{const ops=seeded();const before=JSON.stringify(ops);F.enrich(ops);assert.equal(JSON.stringify(ops),before);assert.equal(ops.find(o=>o.id==='0007').invoices[0].lines.reduce((n,l)=>n+l.billed,0),3960);});
check('câmbio sem conversão é não aplicável, não pendente',()=>{const op=seeded()[0];op.freight.fx['FAT-0011']={applicable:false,reason:'Liquidação em USD confirmada'};assert.equal(F.exchange(op,op.invoices[0]).status,'na');});
console.log(`${n} verificações de frete aprovadas.`);
