const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const path = require('node:path');
const context = vm.createContext({structuredClone, localStorage:{getItem:()=>null}, document:{querySelector:()=>({addEventListener(){}}),addEventListener(){}},window:{addEventListener(){}}});
const source = fs.readFileSync(path.join(__dirname,'../../public/prototypes/centrix-configuracoes/base.js'),'utf8') + '\n' + fs.readFileSync(path.join(__dirname,'../../public/prototypes/centrix-configuracoes/configuracoes.js'),'utf8').replace(/render\(\);\s*$/,'');
vm.runInContext(source,context);
const run=s=>vm.runInContext(s,context);
let total=0;
function check(name,expression){assert.ok(run(expression),name);total++;console.log('PASS '+name);}
check('supplier and exporter share one company', `company('east').roles.includes('Fornecedor') && company('east').roles.includes('Exportador')`);
check('company requires role', `validate('company',{name:'New',roles:[]},'').includes('papel')`);
check('duplicate company requires identity review', `validate('company',{...company('east')},'').includes('mesmo nome')`);
check('supplier role cannot orphan route', `validate('company',{...company('east'),roles:['Importador']},'east').includes('fornecedor/exportador')`);
check('unchanged route with history remains editable', `validate('route',{...route('ningbo')},'ningbo') === ''`);
check('history route cannot change supplier', `validate('route',{...route('ningbo'),supplier:'nord'},'ningbo').includes('casos demonstrativos')`);
check('history route cannot change pickup', `validate('route',{...route('ningbo'),pickup:''},'ningbo').includes('casos demonstrativos')`);
check('duplicate route rejected', `validate('route',{...route('ningbo')},'').includes('já está cadastrada')`);
check('incompatible maritime airport rejected', `validate('route',{...route('ningbo'),from:'frankfurt'},'').includes('devem ser portos')`);
check('repeated connection rejected', `validate('route',{...route('ningbo'),via:['ningbo']},'').includes('repetido')`);
check('empty connection rejected', `validate('route',{...route('ningbo'),via:['']},'').includes('conexão')`);
check('local duplicate code rejected', `validate('location',{...loc('ningbo'),name:'Other'},'').includes('já cadastrado')`);
check('linked local type protected', `validate('location',{...loc('ningbo'),type:'Aeroporto'},'ningbo').includes('Preserve o tipo')`);
check('linked local identity edit allowed', `validate('location',{...loc('ningbo'),description:'New note'},'ningbo') === ''`);
check('agent needs declared service', `validate('agent',{name:'New',modes:[]},'').includes('modalidade')`);
run(`agent('alpha').active=false`);
check('blocked agent rejected in new route', `validate('route',{...route('ningbo'),equipment:'different'},'').includes('bloqueado')`);
check('blocked agent preserves original link', `validate('route',{...route('ningbo'),notes:'New note'},'ningbo') === ''`);
check('location and supplier navigation use same route', `relatedRoutes('locais','east-factory')[0].id === relatedRoutes('empresas','east')[0].id`);
check('new entity name does not produce operations', `operations.every(o=>o.company!=='new-company')`);
console.log(`${total} checks passed`);
